### ISSUE TITLE
[1.18.2] MCA 7.2.0 beta 6 Forge crashes while loading

### ISSUE THREAD

**Issue by iosgoodch** [Luke100000/minecraft-comes-alive#113]
Crash log:
```
---- Minecraft Crash Report ----

// I'm sorry, Dave.

Time: 3/7/22, 8:24 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.0.5-universal.jar%23109!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:169) ~[forge-1.18.2-40.0.5-universal.jar%23109!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:877) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.5.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.NamespacedHolderHelper.createIntrusiveHolder(NamespacedHolderHelper.java:154) ~[forge-1.18.2-40.0.5-universal.jar%23109!/:?] {re:classloading}
-- MOD mca --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.5.jar%23107!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.5.jar%23106!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.ExceptionInInitializerError
		at mca.MCAForge.<init>(MCAForge.java:31) ~[minecraft-comes-alive-7.2.0-beta.6-forge.jar%2388!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.5.jar%23107!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.5.jar%23106!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: minecraft-comes-alive-7.2.0-beta.6-forge.jar
	Failure message: Minecraft Comes Alive (mca) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 7.2.0-beta.6
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.IllegalStateException: Registry is already frozen
Stacktrace:
	at net.minecraftforge.registries.NamespacedHolderHelper.createIntrusiveHolder(NamespacedHolderHelper.java:154) ~[forge-1.18.2-40.0.5-universal.jar%23109!/:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedDefaultedWrapper.createIntrusiveHolder(NamespacedDefaultedWrapper.java:199) ~[forge-1.18.2-40.0.5-universal.jar%23109!/:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedDefaultedWrapper.m_203693_(NamespacedDefaultedWrapper.java:33) ~[forge-1.18.2-40.0.5-universal.jar%23109!/:?] {re:classloading}
	at net.minecraft.world.level.block.Block.<init>(Block.java:67) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at mca.block.BlocksMCA.<clinit>(BlocksMCA.java:14) ~[minecraft-comes-alive-7.2.0-beta.6-forge.jar%2388!/:?] {re:classloading}
	at mca.MCAForge.<init>(MCAForge.java:31) ~[minecraft-comes-alive-7.2.0-beta.6-forge.jar%2388!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.5.jar%23107!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.5.jar%23106!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 11.6.3
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2563579192 bytes (2444 MiB) / 2986344448 bytes (2848 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: Radeon Pro 570X
	Graphics card #0 vendor: AMD (0x1002)
	Graphics card #0 VRAM (MB): 4096.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: Revision ID: 0x00c5, ROM Revision: 113-D0008A-042, VBIOS Version: 113-D0008A148L-003, EFI Driver Version: 01.B1.042
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 0.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: Empty
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 0.00
	Memory slot #3 clockSpeed (GHz): -0.00
	Memory slot #3 type: Empty
	Virtual memory max (MB): 20480.00
	Virtual memory used (MB): 13640.63
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 2936.25
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		SuperCircuitMaker2-0.2.3+1.18.2.jar               |Super Circuit Maker           |supercircuitmaker             |0.2.3               |COMMON_SET|Manifest: NOSIGNATURE
		StylishEffects-v3.1.0-1.18.2-Forge.jar            |Stylish Effects               |stylisheffects                |3.1.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		enchantment_lore_forge-1.1.jar                    |Enchantment Lore Forge        |enchantment_lore_forge        |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		bigbrain-1.4.1.jar                                |Big Brain                     |bigbrain                      |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.2.0-beta.6-forge.jar      |Minecraft Comes Alive         |mca                           |7.2.0-beta.6        |ERROR     |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.0.125.jar                          |Just Enough Items             |jei                           |9.5.0.125           |COMMON_SET|Manifest: NOSIGNATURE
		VisualWorkbench-v3.2.0-1.18.2-Forge.jar           |Visual Workbench              |visualworkbench               |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		LibraryFerret-Forge-1.18.2-1.0.3.jar              |Library ferret                |libraryferret                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		torohealth-1.18-forge-2.jar                       |ToroHealth                    |torohealth                    |1.18-forge-2        |COMMON_SET|Manifest: NOSIGNATURE
		villagernames_1.18.2-3.5.jar                      |Villager Names                |villagernames                 |3.5                 |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+6.jar                   |Clumps                        |clumps                        |8.0.0+6             |COMMON_SET|Manifest: NOSIGNATURE
		Just-Another-Rotten-Flesh-to-Leather-Mod-1.18.1.ja|JRFTL                         |jrftl                         |1.4                 |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.0beta16.jar                 |Journeymap                    |journeymap                    |5.8.0beta16         |COMMON_SET|Manifest: NOSIGNATURE
		exlineawnings-1.18.jar                            |Exline's Awnings              |exlineawnings                 |1.18                |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-1.18.1-5.0.0.2.jar                 |Comforts                      |comforts                      |1.18.1-5.0.0.2      |COMMON_SET|Manifest: NOSIGNATURE
		moreminecarts-1.4.5.jar                           |More Minecarts                |moreminecarts                 |1.4.5               |COMMON_SET|Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		forge-branders-spawnermod-1.18.2-1.8.14.jar       |Enhanced Mob Spawners         |spawnermod                    |1.8.14              |COMMON_SET|Manifest: NOSIGNATURE
		Uncrafted-1.18-(4.0.0pre1).jar                    |Uncrafted                     |uncrafted                     |4.0.0pre1           |COMMON_SET|Manifest: NOSIGNATURE
		BeeFix-1.18-1.0.0.4.jar                           |Bee Fix                       |beefix                        |1.0.0.4             |COMMON_SET|Manifest: NOSIGNATURE
		azalea-FORGE-3.1.1.jar                            |Better Azalea                 |azalea                        |3.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		bedspreads-forge-1.18.1-5.1.0.5.jar               |Bedspreads                    |bedspreads                    |1.18.1-5.1.0.5      |COMMON_SET|Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.18.2-(v.3.0.1).jar   |Additional Structures         |additionalstructures          |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		PickUpNotifier-v3.2.0-1.18.2-Forge.jar            |Pick Up Notifier              |pickupnotifier                |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		medieval_paintings-2.2.jar                        |Medieval Paintings            |medieval_paintings            |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		Terralith_v2.1.3_Fabric+Forge.jar                 |Terralith                     |terralith                     |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.0.5-universal.jar                 |Forge                         |forge                         |40.0.5              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		chalk-1.18.1-1.2.0.jar                            |Chalk                         |chalk                         |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		TKLib-0.0.8+1.18.1.jar                            |TKLib                         |tklib                         |0.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		additionalredstone-1.18.1-1.0.3.jar               |Additional Redstone           |additionalredstone            |1.18.1 - 1.0.3      |COMMON_SET|Manifest: NOSIGNATURE
		AwesomeDungeonOcean-Forge-1.18.2-2.0.4.jar        |Awesome Dungeon Ocean         |awesomedungeonocean           |2.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.11              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		[1.18.1]Gender-1.9.1.jar                          |Gender                        |gender                        |1.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		aquatictorches-1.18-1.1.0.jar                     |Aquatic Torches               |aquatictorches                |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16b-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16b             |COMMON_SET|Manifest: NOSIGNATURE
		movingelevators-1.3.4-mc1.18.jar                  |Moving Elevators              |movingelevators               |1.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		Craftable+Saddles+[1.18+All]-1.4.jar              |Craftable Saddles             |craftable_saddles             |1.4                 |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.6.3.jar                   |Curios API                    |curios                        |1.18.2-5.0.6.3      |COMMON_SET|Manifest: NOSIGNATURE
		AdvancedCombatRemake-1.4-1.18.jar                 |AdvancedCombat                |advancedcombat                |1.0-SNAPSHOT        |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.2-4.24.jar                        |Collective                    |collective                    |4.24                |COMMON_SET|Manifest: NOSIGNATURE
		DramaticDoors-1.18.2-1.5.2.jar                    |Dramatic Doors                |dramaticdoors                 |1.18.2-1.5.2        |COMMON_SET|Manifest: NOSIGNATURE
		Gobber2-Forge-1.18.2-2.6.22.jar                   |Gobber 2                      |gobber2                       |2.6.22              |COMMON_SET|Manifest: NOSIGNATURE
		AmbientEnvironment-forge-1.18.2-7.0+18.jar        |Ambient Environment           |ambientenvironment            |7.0+18              |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.0.30.jar                           |Architectury                  |architectury                  |4.0.30              |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.3.0.jar                  |AppleSkin                     |appleskin                     |2.3.0+mc1.18        |COMMON_SET|Manifest: NOSIGNATURE
		globalxp-1.18.1-1.9.1.jar                         |Global XP                     |globalxp                      |1.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v3.3.1-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.1               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Aquaculture-1.18.2-2.3.4.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.4        |COMMON_SET|Manifest: NOSIGNATURE
		CleanView-1.18.2-v1.jar                           |CleanView                     |cleanview                     |1.18.2-v1           |COMMON_SET|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		geckolib-1.18-forge-3.0.12.jar                    |GeckoLib                      |geckolib3                     |3.0.12              |COMMON_SET|Manifest: NOSIGNATURE
		creeperoverhaul-1.18.2-1.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		betterfoliage-3.0.3.jar                           |Better Foliage                |betterfoliage                 |3.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		TradingPost-v3.2.0-1.18.2-Forge.jar               |Trading Post                  |tradingpost                   |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
	Crash Report UUID: e5a80a9a-b999-4c01-a113-2498ff8b2039
	FML: 40.0
	Forge: net.minecraftforge:40.0.5
```

**Comment by iosgoodch** [comment]
I have tested the 7.2.0 beta 8 forge build and this defect appears to be fixed. Thanks for taking care of it so quickly. Sorry I did not fill out the issue correctly. I'll do it right next time.
