### ISSUE TITLE
Server thread/FATAL payload error

### ISSUE THREAD

**Issue by gamerpotion** [Luke100000/minecraft-comes-alive#208]
Hi,
I have MCA running on a 1.18.1 server and have started seeing the following in the server's console logs.  Something to do with Payload may not be larger than 1048576 bytes

Is there any way to resolve this please?

```
[09.05 22:55:00] [Server] [Server thread/FATAL]: Error executing task on Server
[09.05 22:55:00] [Server] java.lang.IllegalArgumentExceptionPayload may not be larger than 1048576 bytes
[09.05 22:55:00] [Server] 	at net.minecraft.class_2658.<init>(class_2658.java:39) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.createPlayC2SPacket(ServerNetworkingImpl.java:44) ~[fabric-networking-api-v1-1.0.19+d7c144a865-dce01c891e65d5dc.jar:?]
[09.05 22:55:00] [Server] 	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.createS2CPacket(ServerPlayNetworking.java:212) ~[fabric-networking-api-v1-1.0.19+d7c144a865-dce01c891e65d5dc.jar:?]
[09.05 22:55:00] [Server] 	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.send(ServerPlayNetworking.java:251) ~[fabric-networking-api-v1-1.0.19+d7c144a865-dce01c891e65d5dc.jar:?]
[09.05 22:55:00] [Server] 	at mca.fabric.cobalt.network.NetworkHandlerImpl.sendToPlayer(NetworkHandlerImpl.java:43) ~[minecraft-comes-alive-7.2.1+1.18.1-fabric.jar:?]
[09.05 22:55:00] [Server] 	at mca.cobalt.network.NetworkHandler.sendToPlayer(NetworkHandler.java:17) ~[minecraft-comes-alive-7.2.1+1.18.1-fabric.jar:?]
[09.05 22:55:00] [Server] 	at mca.network.c2s.GetFamilyRequest.receive(GetFamilyRequest.java:40) ~[minecraft-comes-alive-7.2.1+1.18.1-fabric.jar:?]
[09.05 22:55:00] [Server] 	at mca.fabric.cobalt.network.NetworkHandlerImpl.lambda$registerMessage$0(NetworkHandlerImpl.java:24) ~[minecraft-comes-alive-7.2.1+1.18.1-fabric.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
[09.05 22:55:00] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Luke100000** [comment]
Someone used the whistle with a massive family and/or heavy villager data (e.g. extremely full inventory). Should be fixed in alpha 3 but I can't imagine how anyone can exceed the limit. In alpha 3 it will start crashing at around over 500 family members.
