### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by KstarMillion** [Luke100000/minecraft-comes-alive#229]
```
[26May2022 19:46:18.809] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, King_Million, --version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, a059582ea935431faf25a7085267a45c, --accessToken, ????????, --clientId, ZTI1Y2JhMDQtYmUzYy00ZDM5LTk4ZjEtYTI1OGM0MDY3N2Zh, --xuid, 2535467421035533, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[26May2022 19:46:18.969] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[26May2022 19:46:20.452] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Kaiden%20Small/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[26May2022 19:46:23.515] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: minecraft
[26May2022 19:46:33.717] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[26May2022 19:46:33.957] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft\assets, --uuid, a059582ea935431faf25a7085267a45c, --username, King_Million, --assetIndex, 1.18, --accessToken, ????????, --clientId, ZTI1Y2JhMDQtYmUzYy00ZDM5LTk4ZjEtYTI1OGM0MDY3N2Zh, --xuid, 2535467421035533, --userType, msa, --versionType, release]
[26May2022 19:46:35.187] [main/WARN] [mixin/]: Error loading class: me/cominixo/betterf3/modules/TargetModule (java.lang.ClassNotFoundException: me.cominixo.betterf3.modules.TargetModule)
[26May2022 19:46:35.187] [main/WARN] [mixin/]: @Mixin target me.cominixo.betterf3.modules.TargetModule was not found securitycraft.mixins.json:f3.BetterF3TargetModuleMixin
[26May2022 19:46:36.257] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/ai/brain/schedule/Activity (java.lang.ClassNotFoundException: net.minecraft.entity.ai.brain.schedule.Activity)
[26May2022 19:46:36.257] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.ai.brain.schedule.Activity was not found mca.mixin.json:MixinActivity
[26May2022 19:46:36.257] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/passive/horse/AbstractHorseEntity (java.lang.ClassNotFoundException: net.minecraft.entity.passive.horse.AbstractHorseEntity)
[26May2022 19:46:36.257] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.passive.horse.AbstractHorseEntity was not found mca.mixin.json:MixinHorseBaseEntity
[26May2022 19:46:36.257] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/ai/brain/memory/MemoryModuleType (java.lang.ClassNotFoundException: net.minecraft.entity.ai.brain.memory.MemoryModuleType)
[26May2022 19:46:36.257] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.ai.brain.memory.MemoryModuleType was not found mca.mixin.json:MixinMemoryModuleType
[26May2022 19:46:36.257] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/player/PlayerEntity (java.lang.ClassNotFoundException: net.minecraft.entity.player.PlayerEntity)
[26May2022 19:46:36.265] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.player.PlayerEntity was not found mca.mixin.json:MixinPlayerEntity
[26May2022 19:46:36.265] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/chunk/ChunkPrimer (java.lang.ClassNotFoundException: net.minecraft.world.chunk.ChunkPrimer)
[26May2022 19:46:36.265] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.chunk.ChunkPrimer was not found mca.mixin.json:MixinProtoChunk
[26May2022 19:46:36.265] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/ai/brain/sensor/SensorType (java.lang.ClassNotFoundException: net.minecraft.entity.ai.brain.sensor.SensorType)
[26May2022 19:46:36.265] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.ai.brain.sensor.SensorType was not found mca.mixin.json:MixinSensorType
[26May2022 19:46:36.265] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/server/ServerWorld (java.lang.ClassNotFoundException: net.minecraft.world.server.ServerWorld)
[26May2022 19:46:36.265] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.server.ServerWorld was not found mca.mixin.json:MixinServerWorld
[26May2022 19:46:36.265] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/EntityPredicate (java.lang.ClassNotFoundException: net.minecraft.entity.EntityPredicate)
[26May2022 19:46:36.265] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.EntityPredicate was not found mca.mixin.json:MixinTargetPredicate
[26May2022 19:46:36.273] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/merchant/villager/VillagerEntity (java.lang.ClassNotFoundException: net.minecraft.entity.merchant.villager.VillagerEntity)
[26May2022 19:46:36.273] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.merchant.villager.VillagerEntity was not found mca.mixin.json:MixinVillagerEntity
[26May2022 19:46:36.273] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/monster/ZombieVillagerEntity (java.lang.ClassNotFoundException: net.minecraft.entity.monster.ZombieVillagerEntity)
[26May2022 19:46:36.273] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.monster.ZombieVillagerEntity was not found mca.mixin.json:MixinZombieVillagerEntity
[26May2022 19:46:36.273] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/network/play/ClientPlayNetHandler (java.lang.ClassNotFoundException: net.minecraft.client.network.play.ClientPlayNetHandler)
[26May2022 19:46:36.305] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.network.play.ClientPlayNetHandler was not found mca.mixin.json:MixinClientPlayNetworkHandler
[26May2022 19:46:36.305] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.ClassNotFoundException: net.minecraft.client.entity.player.ClientPlayerEntity)
[26May2022 19:46:36.305] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found mca.mixin.json:client.MixinClientPlayerEntity
[26May2022 19:46:36.305] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/FontRenderer (java.lang.ClassNotFoundException: net.minecraft.client.gui.FontRenderer)
[26May2022 19:46:36.305] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.FontRenderer was not found mca.mixin.json:client.MixinTextRenderer
[26May2022 19:46:36.305] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/resources/ClientLanguageMap (java.lang.ClassNotFoundException: net.minecraft.client.resources.ClientLanguageMap)
[26May2022 19:46:36.305] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.resources.ClientLanguageMap was not found mca.mixin.json:client.MixinTranslationStorage
[26May2022 19:47:07.716] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/Kaiden%20Small/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2366!/assets/.mcassetsroot' uses unexpected schema
[26May2022 19:47:07.718] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/Kaiden%20Small/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2366!/data/.mcassetsroot' uses unexpected schema
[26May2022 19:47:07.812] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[26May2022 19:47:09.450] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: King_Million
[26May2022 19:47:10.203] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[26May2022 19:47:13.664] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §emca§r requires §6minecraft§r §o1.16.5 or above, and below 1.17§r
§7Currently, §6minecraft§r§7 is §o1.18.2
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.18.2-40.1.0.jar%2367!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:94) ~[fmlcore-1.18.2-40.1.0.jar%2367!/:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:126) ~[fmlcore-1.18.2-40.1.0.jar%2367!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.18.2-40.1.0-universal.jar%2370!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:113) ~[forge-1.18.2-40.1.0-universal.jar%2370!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.18.2-40.1.0-universal.jar%2370!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:458) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[26May2022 19:47:14.749] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[26May2022 19:47:15.545] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[26May2022 19:47:15.550] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[26May2022 19:47:18.934] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state
[26May2022 19:47:19.181] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[26May2022 19:47:19.278] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[26May2022 19:47:19.279] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[26May2022 19:47:19.280] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[26May2022 19:47:19.771] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: Default
[26May2022 19:47:20.424] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state
[26May2022 19:47:22.623] [Worker-Main-7/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:26.292] [Worker-Main-5/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:36.598] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:37.128] [Worker-Main-8/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:39.897] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:39.936] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:39.983] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:40.023] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:40.035] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:40.080] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[26May2022 19:47:40.970] [Render thread/INFO] [com.mojang.blaze3d.audio.Library/]: OpenAL initialized on device OpenAL Soft on Speakers (Intel® Smart Sound Technology (Intel® SST))
[26May2022 19:47:40.972] [Render thread/INFO] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Sound engine started
[26May2022 19:47:41.579] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[26May2022 19:47:41.626] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:41.627] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[26May2022 19:47:41.629] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:41.630] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[26May2022 19:47:41.632] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:41.632] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[26May2022 19:47:41.635] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:41.635] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[26May2022 19:47:41.636] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:41.636] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[26May2022 19:47:41.638] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:41.638] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[26May2022 19:47:41.639] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:43.057] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state
[26May2022 19:47:43.671] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:43.677] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.118] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.128] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.130] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.132] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.133] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.137] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.137] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.145] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.148] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.149] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.184] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.186] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.187] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.189] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.191] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.194] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.196] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.197] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.230] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.231] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[26May2022 19:47:44.232] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[26May2022 19:47:46.071] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[26May2022 19:47:47.028] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[26May2022 19:47:47.113] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:47.116] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[26May2022 19:47:47.117] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:47.117] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[26May2022 19:47:47.118] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[26May2022 19:47:48.563] [Render thread/FATAL] [net.minecraftforge.client.loading.ClientModLoader/]: Crash repor
```

**Comment by Luke100000** [comment]
`net.minecraftforge.fml.ModLoadingException: Mod §emca§r requires §6minecraft§r §o1.16.5 or above, and below 1.17§r`
Use MCA for 1.18.2, not 1.16.5.
