### ISSUE TITLE
mca alpha 7.3.0 crashes when launching game

### ISSUE THREAD

**Issue by laurence-1** [Luke100000/minecraft-comes-alive#231]
```
(Fabric) I have architectury, but the mod still won't let me launch the game. I've had this issue on other mod versions, but it works just fine when I remove mca.


---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/28/22, 2:01 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mca'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at mca.entity.ai.relationship.AgeState.getMaxAge(AgeState.java:28)
	at mca.entity.VillagerEntityMCA.<clinit>(VillagerEntityMCA.java:101)
	at dev.architectury.registry.level.entity.fabric.EntityAttributeRegistryImpl.register(EntityAttributeRegistryImpl.java:31)
	at dev.architectury.registry.level.entity.EntityAttributeRegistry.register(EntityAttributeRegistry.java)
	at mca.entity.EntitiesMCA.lambda$register$5(EntitiesMCA.java:59)
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.register(RegistriesImpl.java:223)
	at dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:76)
	at mca.entity.EntitiesMCA.bootstrap(EntitiesMCA.java:48)
	at mca.fabric.MCAFabric.onInitialize(MCAFabric.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 0.5 at line 41 column 34 path $.interactionChanceFatigue
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:229)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:219)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:901)
	at mca.Config.loadOrCreate(Config.java:159)
	at mca.Config.<clinit>(Config.java:15)
	... 21 more
Caused by: java.lang.NumberFormatException: Expected an int but was 0.5 at line 41 column 34 path $.interactionChanceFatigue
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1203)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
	... 28 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		AMSIExt.dll:McAfee Cloud AV ThirdParty Ext:22,5,147,0:McAfee, LLC.
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2203.5 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.19041.1682 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.1503 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll
		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jna12697406197892487091.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.1682 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		win32u.dll:Win32u:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 452854672 bytes (431 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=23.20.16.4973
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 14030.22
	Virtual memory used (MB): 8940.94
	Swap memory total (MB): 1856.00
	Swap memory used (MB): 92.81
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury 4.4.60
		besmirchment 1.18.2-11
			playerabilitylib 1.5.0
			reach-entity-attributes 2.1.1
			terraform-wood-api-v1 3.0.0
		bewitchment 1.18-20
			fabric-permissions-api-v0 0.1-SNAPSHOT
			step-height-entity-attribute 1.0.0
		bwplus 1.18.2-16
		byg 1.4
		cloth-config 6.2.57
			cloth-basic-math 0.6.0
		disable_custom_worlds_advice 2.0
		fabric 0.53.0+1.18.2
			fabric-api-base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1 1.6.0+2373a54560
			fabric-biome-api-v1 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1 1.1.12+3ac43d9560
			fabric-command-api-v1 1.1.9+d7c144a860
			fabric-commands-v0 0.2.8+b4f4f6cd60
			fabric-containers-v0 0.1.21+d7c144a860
			fabric-content-registries-v0 3.0.4+d82b939260
			fabric-convention-tags-v1 1.0.1+474e4f7960
			fabric-crash-report-info-v1 0.2.0+a6b0947860
			fabric-dimensions-v1 2.1.17+2540745460
			fabric-entity-events-v1 1.4.8+d7c144a860
			fabric-events-interaction-v0 0.4.19+d7c144a860
			fabric-events-lifecycle-v0 0.2.15+d7c144a860
			fabric-game-rule-api-v1 1.0.13+d7c144a860
			fabric-item-api-v1 1.5.0+85719ab760
			fabric-item-groups-v0 0.3.12+91896a4960
			fabric-key-binding-api-v1 1.0.12+54e5b2ec60
			fabric-keybindings-v0 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1 2.0.3+2d83e92c60
			fabric-loot-tables-v1 1.0.11+d7c144a860
			fabric-mining-level-api-v1 2.1.1+81ea5b3c60
			fabric-models-v0 0.3.6+d7c144a860
			fabric-networking-api-v1 1.0.21+d882b91560
			fabric-networking-v0 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1 2.1.1+032c981d60
			fabric-particles-v1 0.2.12+526dc1ac60
			fabric-registry-sync-v0 0.9.8+0d9ab37260
			fabric-renderer-api-v1 0.4.13+d882b91560
			fabric-renderer-indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1 0.3.7+d7c144a860
			fabric-rendering-fluids-v1 2.0.2+54e5b2ec60
			fabric-rendering-v0 1.1.13+b4f4f6cd60
			fabric-rendering-v1 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
			fabric-resource-loader-v0 0.5.0+2afceb2960
			fabric-screen-api-v1 1.0.10+d882b91560
			fabric-screen-handler-api-v1 1.2.0+1f6558e860
			fabric-textures-v0 1.0.12+3ac43d9560
			fabric-transfer-api-v1 1.6.1+f4563ac860
			fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860
		fabric-language-kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2
		fabricloader 0.13.3
		geckolib3 3.0.42
			com_eliotlash_mclib_mclib 18
			com_eliotlash_molang_molang 18
		haema 1.9.5+1.18.2
			cardinal-components-base 4.1.4
			cardinal-components-entity 4.1.4
			satin 1.7.2
		icarus 1.11
		impersonate 2.5.0
		iris 1.2.4-build.38
			org_anarres_jcpp 1.4.14
		java 17
		lithium 0.7.9
		mca 7.3.0
		minecraft 1.18.2
		moborigins 1.8.1
		modmenu 3.1.1
		origins 1.4.1
			apoli 2.3.3
				additionalentityattributes 1.0.0+1.18.2
				calio 1.5.1
		origins-classes 1.3.0
		patchouli 1.18.2-67-FABRIC
			fiber 0.23.0-2
		pehkui 3.2.2+1.14.4-1.19
			kanos_config 0.2.0+1.14.4-1.19
		phosphor 0.8.1
		roughlyenoughitems 8.1.449
		sodium 0.4.1+build.15
			org_joml_joml 1.10.2
		terrablender 1.1.0.101
			com_electronwill_night-config_core 3.6.4
			com_electronwill_night-config_toml 3.6.4
		torohealth 1.18-fabric-2
		trinkets 3.3.0
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by Luke100000** [comment]
I will rip out architectury soon, should fix that

**Comment by Luke100000** [comment]
Not sure if its related but do not use `0.5` for `interactionChanceFatigue`, only integers are supported for now
