### ISSUE TITLE
player when entering the server

### ISSUE THREAD

**Issue by lostopkk** [Luke100000/minecraft-comes-alive#232]
```
[15:36:37] [Server thread/INFO]: Alisson377[/26.81.143.55:60639] logged in with entity id 2919 at (5.5, 120.0, -7.5)
[15:36:37] [Server thread/INFO]: Alisson377 joined the game
[15:36:37] [Render thread/INFO]: [CHAT] Alisson377 joined the game
[15:36:37] [Server thread/INFO]: Syncing config to Alisson377 (05cf1a51-190b-476c-9613-6ab8ff1574a3)
[15:36:41] [Server thread/INFO]: Alisson377 has made the advancement [Minecraft Comes Alive]
[15:36:41] [Server thread/INFO]: Alisson377 lost connection: Disconnected
[15:36:41] [Server thread/INFO]: Alisson377 left the game
[15:36:41] [Render thread/INFO]: [CHAT] Alisson377 has made the advancement [Minecraft Comes Alive]
[15:36:41] [Render thread/INFO]: [CHAT] Alisson377 left the game
[15:36:41] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_10711()" because "$$0" is null
	at net.minecraft.class_2507.method_10631(class_2507.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10628(class_2507.java:99) ~[client-intermediary.jar:?]
	at mca.network.NbtDataMessage$Data.writeObject(NbtDataMessage.java:35) ~[minecraft-comes-alive-7.3.0-fabric.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1201) ~[?:?]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1526) ~[?:?]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582) ~[?:?]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539) ~[?:?]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354) ~[?:?]
	at mca.cobalt.network.Message.encode(Message.java:25) ~[minecraft-comes-alive-7.3.0-fabric.jar:?]
	at mca.fabric.cobalt.network.NetworkHandlerImpl.sendToPlayer(NetworkHandlerImpl.java:42) ~[minecraft-comes-alive-7.3.0-fabric.jar:?]
	at mca.cobalt.network.NetworkHandler.sendToPlayer(NetworkHandler.java:17) ~[minecraft-comes-alive-7.3.0-fabric.jar:?]
	at mca.network.c2s.GetVillagerRequest.receive(GetVillagerRequest.java:35) ~[minecraft-comes-alive-7.3.0-fabric.jar:?]
	at mca.fabric.cobalt.network.NetworkHandlerImpl.lambda$registerMessage$0(NetworkHandlerImpl.java:24) ~[minecraft-comes-alive-7.3.0-fabric.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$bbd000$redirectExecuteTask(class_1255.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:4788) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by TheButterbrotMan** [comment]
Maybe connected to https://github.com/Luke100000/minecraft-comes-alive/issues/237
