### ISSUE TITLE
bug on mca players that try to plant sth?

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#252]
```log
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5998(net.minecraft.class_1268)" because "player" is null
        at net.minecraft.class_1792.handler$bbg000$useBlinking(class_1792.java:2052)
        at net.minecraft.class_1792.method_7836(class_1792.java)
        at net.minecraft.class_1747.method_7884(class_1747.java:54)
        at net.minecraft.class_1799.method_7981(class_1799.java:250)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.lambda$plantSeeds$7(HarvestingTask.java:230)
```

Looks like there is a missing NPE check. But I do not understand where, exactly. However, I cannot restart my server now, as this bug comes up as soon as the world has been generated.

The full crash report:
```log
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/16/22, 10:09 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5998(net.minecraft.class_1268)" because "player" is null
        at net.minecraft.class_1792.handler$bbg000$useBlinking(class_1792.java:2052)
        at net.minecraft.class_1792.method_7836(class_1792.java)
        at net.minecraft.class_1747.method_7884(class_1747.java:54)
        at net.minecraft.class_1799.method_7981(class_1799.java:250)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.lambda$plantSeeds$7(HarvestingTask.java:230)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Streams.java:82)
        at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.plantSeeds(HarvestingTask.java:232)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.keepRunning(HarvestingTask.java:178)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.method_18924(HarvestingTask.java:32)
        at net.minecraft.class_4097.method_18923(class_4097.java:63)
        at net.minecraft.class_4095.method_19545(class_4095.java:527)
        at net.minecraft.class_4095.method_19542(class_4095.java:472)
        at net.minecraft.class_1646.method_5958(class_1646.java:277)
        at net.minecraft.class_1308.method_6023(class_1308.java:759)
        at net.minecraft.class_1309.method_6007(class_1309.java:2609)
        at net.minecraft.class_1308.method_6007(class_1308.java:546)
        at net.minecraft.class_1296.method_6007(class_1296.java:127)
        at mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:547)
        at net.minecraft.class_1309.method_5773(class_1309.java:2354)
        at net.minecraft.class_1308.method_5773(class_1308.java:346)
        at net.minecraft.class_1646.method_5773(class_1646.java:318)
        at mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:603)
        at net.minecraft.class_3218.method_18762(class_3218.java:702)
        at net.minecraft.class_1937.method_18472(class_1937.java:485)
        at net.minecraft.class_3218.method_31420(class_3218.java:363)
        at net.minecraft.class_5574.method_31791(class_5574.java:54)
        at net.minecraft.class_3218.method_18765(class_3218.java:331)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
        at net.minecraft.class_3176.method_3813(class_3176.java:322)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.class_1792.handler$bbg000$useBlinking(class_1792.java:2052)
        at net.minecraft.class_1792.method_7836(class_1792.java)
        at net.minecraft.class_1747.method_7884(class_1747.java:54)
        at net.minecraft.class_1799.method_7981(class_1799.java:250)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.lambda$plantSeeds$7(HarvestingTask.java:230)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Streams.java:82)
        at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.plantSeeds(HarvestingTask.java:232)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.keepRunning(HarvestingTask.java:178)
        at mca.entity.ai.brain.tasks.chore.HarvestingTask.method_18924(HarvestingTask.java:32)
        at net.minecraft.class_4097.method_18923(class_4097.java:63)
        at net.minecraft.class_4095.method_19545(class_4095.java:527)
        at net.minecraft.class_4095.method_19542(class_4095.java:472)
        at net.minecraft.class_1646.method_5958(class_1646.java:277)
        at net.minecraft.class_1308.method_6023(class_1308.java:759)
        at net.minecraft.class_1309.method_6007(class_1309.java:2609)
        at net.minecraft.class_1308.method_6007(class_1308.java:546)
        at net.minecraft.class_1296.method_6007(class_1296.java:127)
        at mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:547)
        at net.minecraft.class_1309.method_5773(class_1309.java:2354)
        at net.minecraft.class_1308.method_5773(class_1308.java:346)
        at net.minecraft.class_1646.method_5773(class_1646.java:318)
        at mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:603)
        at net.minecraft.class_3218.method_18762(class_3218.java:702)
        at net.minecraft.class_1937.method_18472(class_1937.java:485)
        at net.minecraft.class_3218.method_31420(class_3218.java:363)
        at net.minecraft.class_5574.method_31791(class_5574.java:54)
        at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
        Entity Type: mca:male_villager (mca.entity.VillagerEntityMCA)
        Entity ID: 53
        Entity Name: Jacob
        Entity's Exact location: -20.30, 66.00, 28.42
        Entity's Block location: World: (-21,66,28), Section: (at 11,2,12 in -2,4,1; chunk contains blocks -32,-64,16 to -17,319,31), Region: (-1,0; contains chunks -
32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
        Entity's Momentum: 0.00, -0.08, 0.00
        Entity's Passengers: []
        Entity's Vehicle: null
Stacktrace:
        at net.minecraft.class_1937.method_18472(class_1937.java:485)
        at net.minecraft.class_3218.method_31420(class_3218.java:363)
        at net.minecraft.class_5574.method_31791(class_5574.java:54)
        at net.minecraft.class_3218.method_18765(class_3218.java:331)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
        at net.minecraft.class_3176.method_3813(class_3176.java:322)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
        All players: 0 total; []
        Chunk stats: 2209
        Level dimension: minecraft:overworld
        Level spawn location: World: (0,66,0), Section: (at 0,2,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, b
locks 0,-64,0 to 511,319,511)
        Level time: 72653462 game time, 75292945 day time
        Level name: world1.18.2
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
        Level weather: Rain time: 29876 (now: false), thunder time: 63694 (now: false)
        Known server brands: fabric
        Level was modded: true
        Level storage version: 0x04ABD - Anvil
Stacktrace:
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
        at net.minecraft.class_3176.method_3813(class_3176.java:322)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
        Minecraft Version: 1.18.2
        Minecraft Version ID: 1.18.2
        Operating System: Linux (amd64) version 5.10.0-13-amd64
        Java Version: 17.0.2, Debian
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
        Memory: 3335839744 bytes (3181 MiB) / 4399824896 bytes (4196 MiB) up to 6291456000 bytes (6000 MiB)
        CPUs: 4
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
        Identifier: Intel64 Family 6 Model 79 Stepping 1
        Microarchitecture: Broadwell (Server)
        Frequency (GHz): 2.20
        Number of physical packages: 1
        Number of physical CPUs: 4
        Number of logical CPUs: 4
        Graphics card #0 name: Device
        Graphics card #0 vendor: Vendor (0x1234)
        Graphics card #0 VRAM (MB): 16.00
        Graphics card #0 deviceId: 0x1111
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MB): 3978.40
        Virtual memory used (MB): 6481.25
        Swap memory total (MB): 0.00
        Swap memory used (MB): 0.00
        JVM Flags: 1 total; -Xmx6000M
        Fabric Mods: 
                architectury: Architectury 4.1.44
                blossom: Blossom 1.18.2-1.0.4
                byg: Oh The Biomes You'll Go 1.4-RC-8
                cardinal-components-base: Cardinal Components API (base) 4.1.3
                cardinal-components-entity: Cardinal Components API (entities) 4.1.3
                cloth-basic-math: cloth-basic-math 0.6.1
                cloth-config: Cloth Config v6 6.2.62
                com_electronwill_night-config_core: core 3.6.4
                com_electronwill_night-config_toml: toml 3.6.4
                com_eliotlash_mclib_mclib: mclib 18
                com_eliotlash_molang_molang: molang 18
                com_typesafe_config: config 1.4.1
                crockpot: Crock Pot 0.7.4+1.18.2
                croptopia: Croptopia 1.8.3
                emerald_tools: Emerald Tools 1.3.38
                fabric: Fabric API 0.51.1+1.18.2
                fabric-api-base: Fabric API Base 0.4.4+d7c144a860
                fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
                fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
                fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
                fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
                fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
                fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
                fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
                fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
                fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
                fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
                fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
                fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
                fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
                fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
                fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
                fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
                fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
                fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
                fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
                fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
                fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
                fabricloader: Fabric Loader 0.13.3
                farmersdelight: Farmer's Delight 1.18.2-0.2.1
                fiber: fiber 0.23.0-2
                geckolib3: Geckolib 3.0.35
                guardvillagers: Guard Villagers Fabric 1.18.2-1.0.11
                io_leangen_geantyref_geantyref: geantyref 1.3.11
                java: OpenJDK 64-Bit Server VM 17
                lithium: Lithium 0.7.9
                mca: Minecraft Comes Alive 7.2.0+1.18.2
                megaparrot: Megaparrot 1.0.4
                minecraft: Minecraft 1.18.2
                more_gems: More Gems 1.3.61
                moreberries: More Berries 1.4.6
                mostructures: Mo' Structures 1.4.1+1.18.2
                omega-config: OmegaConfig 1.2.3-1.18.1
                org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
                org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
                org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
                org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
                org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
                org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
                org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
                org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
                org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
                org_spongepowered_configurate-core: configurate-core 4.1.2
                org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
                patchouli: Patchouli 1.18.2-66-FABRIC
                piglib: Piglib 1.1.1
                pugh_lib: Pugh Lib 1.3.0
                pugh_tools: Pugh Tools 1.2.0
                quickiefabric: quickiefabric 1.18.2.1
                roughlyenoughitems: Roughly Enough Items 8.0.442
                terrablender: TerraBlender 1.1.0.99
                trinkets: Trinkets 3.3.0
                veggie_way: The Veggie Way 1.2.31
                voicechat: Simple Voice Chat 1.18.2-2.2.26
                waystones: Waystones 2.5.0
                xaerominimap: Xaero's Minimap 22.9.2
                xaeroworldmap: Xaero's World Map 1.21.2
        Server Running: true
        Player Count: 0 / 12; []
        Data Packs: vanilla, Fabric Mods
        World Generation: Stable
        Is Modded: Definitely; Server brand changed to 'fabric'
        Type: Dedicated Server (map_server.txt)
```

**Comment by Luke100000** [comment]
Should be fixed in newer versions, can you please confirm this?

**Comment by ghost** [comment]
where exactly do I find a fabric version for minecraft 1.82.2? I have found so many places and do not know which is the right one.

**Comment by Luke100000** [comment]
On the CurseForge or modrinth: https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn/files/all

**Comment by ghost** [comment]
thanks. I'll try the 7.3.1 version and report here in a minute...

**Comment by ghost** [comment]
Yes, that worked. Issue solved within of 30 minutes, this is a new record for me. Thanks very much!
