### ISSUE TITLE
Rendering entity in world

### ISSUE THREAD

**Issue by alcori** [Luke100000/minecraft-comes-alive#270]
Open inventory with [Rougly Enough Items[Fabric 1.18.2] v8.3.501](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/3851414) and [[Fabric 1.18.2] MCA Reborn - 7.3.4+1.18.2](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn/files/3846689)
AND
Write something in "Search" text-field [Rougly Enough Items].

**Minecraft 1.18.2 Fabric 0.14.8**
**Crash log:**
Description: Rendering entity in world

java.lang.NullPointerException: Cannot read field "width" because "this.data" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at mca.client.resources.ColorPalette.getColor(ColorPalette.java:33)
	at mca.client.render.layer.SkinLayer.getColor(SkinLayer.java:30)
	at mca.client.render.layer.VillagerLayer.renderFinal(VillagerLayer.java:77)
	at mca.client.render.layer.VillagerLayer.render(VillagerLayer.java:69)
	at mca.client.render.layer.VillagerLayer.render(VillagerLayer.java:25)
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:145)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:64)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:42)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:135)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.method_29977(InventoryScreen:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem:1171)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen:152)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawBackground(InventoryScreen:110)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:100)
	at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen:29)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen:90)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mca.client.resources.ColorPalette.getColor(ColorPalette.java:33)
	at mca.client.render.layer.SkinLayer.getColor(SkinLayer.java:30)
	at mca.client.render.layer.VillagerLayer.renderFinal(VillagerLayer.java:77)
	at mca.client.render.layer.VillagerLayer.render(VillagerLayer.java:69)
	at mca.client.render.layer.VillagerLayer.method_4199(VillagerLayer.java:25)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:64)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_490.method_25394(class_490.java:90)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 101
	Entity Name: Alcori
	Entity's Exact location: 1725.43, -19.00, -740.33
	Entity's Block location: World: (1725,-19,-741), Section: (at 13,13,11 in 107,-2,-47; chunk contains blocks 1712,-64,-752 to 1727,319,-737), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,-64,-1024 to 2047,319,-513)
	Entity's Momentum: 0.02, -0.08, -0.03
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,Attributes:[{Base:0.0d,Name:"reach-entity-attributes:attack_range"},{Base:0.0d,Name:"playerex:lightning_resistance"},{Base:4.0d,Name:"minecraft:generic.attack_speed"},{Base:0.0d,Name:"reach-entity-attributes:reach"},{Base:0.0d,Name:"playerex:constitution"},{Base:0.0d,Name:"minecraft:generic.knockback_resistance"},{Base:0.0d,Name:"stepheightentityattribute:stepheight"},{Base:0.0d,Name:"minecraft:generic.luck"},{Base:0.0d,Name:"playerex:poison_resistance"},{Base:0.0d,Name:"playerex:ranged_damage"},{Base:0.10000000149011612d,Name:"minecraft:generic.movement_speed"},{Base:0.0d,Name:"playerex:melee_crit_damage"},{Base:0.0d,Name:"playerex:dexterity"},{Base:1.0d,Name:"minecraft:generic.attack_damage"},{Base:0.0d,Name:"playerex:health_regeneration"},{Base:20.0d,Name:"minecraft:generic.max_health"},{Base:0.0d,Name:"playerex:luckiness"},{Base:0.0d,Name:"playerex:ranged_crit_chance"},{Base:0.0d,Name:"playerex:evasion"},{Base:0.0d,Name:"playerex:melee_crit_chance"},{Base:0.0d,Name:"playerex:level"},{Base:0.0d,Name:"playerex:strength"},{Base:0.0d,Name:"minecraft:generic.armor"}],BMLootBlock:0b,BalmData:{},Brain:{memories:{}},DataVersion:2975,DeathTime:0s,EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:-20s,Health:22.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[{Count:1b,Slot:0b,id:"minecraft:iron_pickaxe",tag:{Damage:0}},{Count:1b,Slot:1b,id:"minecraft:iron_axe",tag:{Damage:0}},{Count:1b,Slot:2b,id:"minecraft:iron_sword",tag:{Damage:0}},{Count:38b,Slot:3b,id:"minecraft:cobbled_deepslate"},{Count:15b,Slot:6b,id:"croptopia:nectarine"},{Count:17b,Slot:7b,id:"additionaladditions:glow_stick"},{Count:3b,Slot:8b,id:"minecraft:diamond"},{Count:5b,Slot:10b,id:"minecraft:feather"},{Count:14b,Slot:12b,id:"minecraft:raw_iron"},{Count:11b,Slot:13b,id:"minecraft:spruce_log"},{Count:5b,Slot:14b,id:"croptopia:blueberry_seed"},{Count:18b,Slot:15b,id:"minecraft:oak_log"},{Count:3b,Slot:16b,id:"croptopia:squash_seed"},{Count:1b,Slot:17b,id:"adorn:guide_book"},{Count:2b,Slot:19b,id:"minecraft:gunpowder"},{Count:1b,Slot:21b,id:"betteranimalsplus:boarhead_dark_brown"},{Count:8b,Slot:22b,id:"minecraft:sweet_berries"},{Count:2b,Slot:23b,id:"croptopia:celery_seed"},{Count:1b,Slot:24b,id:"croptopia:blackberry"},{Count:9b,Slot:25b,id:"croptopia:lemon"},{Count:12b,Slot:26b,id:"minecraft:coal"},{Count:2b,Slot:27b,id:"croptopia:blackberry_seed"},{Count:17b,Slot:28b,id:"minecraft:raw_copper"},{Count:2b,Slot:29b,id:"croptopia:blueberry"},{Count:1b,Slot:30b,id:"croptopia:barley_seed"},{Count:2b,Slot:31b,id:"croptopia:strawberry_seed"},{Count:3b,Slot:32b,id:"mythicmetals:raw_tin"},{Count:1b,Slot:34b,id:"croptopia:strawberry"},{Count:63b,Slot:35b,id:"minecraft:cobblestone"},{Count:1b,Slot:-106b,id:"minecraft:lantern"}],Invulnerable:0b,Motion:[0.015019119351307193d,-0.0784000015258789d,-0.03176366539781916d],OnGround:1b,PortalCooldown:0,Pos:[1725.4349925169597d,-19.0d,-740.3313854096606d],Rotation:[237.59875f,-25.614187f],Score:164,SelectedItemSlot:0,SleepTimer:0s,UUID:[I;-1403030589,-384814052,-2069489180,1108779384],XpLevel:4,XpP:0.8424766f,XpSeed:0,XpTotal:164,abilities:{flySpeed:0.05f,flying:0b,instabuild:0b,invulnerable:0b,mayBuild:1b,mayfly:0b,walkSpeed:0.1f},byg:{known_biomes:{minecraft:["minecraft:stony_shore","minecraft:dripstone_caves","minecraft:taiga","minecraft:forest"]}},cardinal_components:{"enchancement:acceleration":{SpeedMultiplier:1.0f},"enchancement:dash":{DashCooldown:20,LastDashCooldown:20,ShouldRefreshDash:0b,WavedashTicks:0},"enchancement:frozen":{ForceLimbDistance:0.0f,ForcedBodyYaw:0.0f,ForcedClientAge:0,ForcedHeadYaw:0.0f,ForcedLimbAngle:0.0f,ForcedPitch:0.0f,ForcedPose:"STANDING",Frozen:0b,TicksFrozen:0},"enchancement:gale":{HasGaleDashed:1b,JumpCooldown:0,JumpsLeft:0,TicksInAir:0},"enchancement:impact":{ImpactCooldown:60,ImpactTicks:0,ShouldRefreshImpact:0b},"enchancement:moving_forward":{MovingForward:0b},"enchancement:strafe":{StrafeCooldown:0,TicksInAir:0},"playerex:player_data":{Modifiers:[{Key:"playerex:constitution",Value:2.0d},{Key:"playerex:luckiness",Value:1.0d},{Key:"playerex:level",Value:5.0d},{Key:"playerex:strength",Value:1.0d},{Key:"playerex:dexterity",Value:1.0d}],NotifiedLevelUp:0b,RefundPoints:0,SkillPoints:0},"things:sock_data":{SockSpeeds:[],SpeedModification:0.0f},"trinkets:trinkets":{chest:{back:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}},cape:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}},necklace:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}}},feet:{shoes:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}}},hand:{glove:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}},ring:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}}},head:{face:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}}},legs:{belt:{Items:[{Count:1b,id:"minecraft:air"}],Metadata:{}}}}},"faux-custom-entity-data:custom":{},foodExhaustionLevel:0.0f,foodLevel:20,foodSaturationLevel:3.6000001f,foodTickTimer:0,magnetismEnabled:1b}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@4d9f1b1b
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (341, 192). Absolute: (683.000000, 384.000000)
	Screen size: Scaled: (683, 384). Absolute: (1366, 768). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Alcori'/101, l='ClientLevel', x=1725.43, y=-19.00, z=-740.33]]
	Chunk stats: 16384, 270
	Level dimension: minecraft:overworld
	Level spawn location: World: (1824,93,-916), Section: (at 0,13,12 in 114,5,-58; chunk contains blocks 1824,-64,-928 to 1839,319,-913), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,-64,-1024 to 2047,319,-513)
	Level time: 169555 game time, 179402 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Luke100000** [comment]
Has it been fixed bei REI? While it is a mod incompatibility, it's most likely fixable from within mca and I would keep that issue open until fixed.

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/187567198-f57256fc-0742-477f-bb4f-aee79de02ef3.png)
Closed as presumed resolved
