### ISSUE TITLE
Villager Entities Bizarre Rendering

### ISSUE THREAD

**Issue by Jurklein** [Luke100000/minecraft-comes-alive#346]
Villager entities get rendered as white or pink dwarf faceless dolls, as in the pictures below:
(before updating architectury to 4.9.83-fabric):
![image](https://user-images.githubusercontent.com/32760403/185505336-d6038c27-5961-4f50-87e0-cf2d75fc5fc7.png)

(after updating architectury):
![image](https://user-images.githubusercontent.com/32760403/185505196-6578cc82-7cb1-4e98-9691-b73803b1fb0c.png)

I'm testing this under the Aternos online server. I cannot reproduce this when hosting on my local machine. What could be the issue?

**Comment by Jurklein** [comment]
client side error:


` <log4j:Event logger="net.minecraft.class_1255" timestamp="1660860536078" level="FATAL" thread="Render thread">
    <log4j:Message><![CDATA[Error executing task on Client]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.IllegalStateException: Invalid entity data item type for field 43 on entity VillagerEntityMCA['entity.mca.female_villager.none'/506, l='ClientLevel', x=-2441.80, y=69.00, z=-818.24]: old={c9c21585-4ca0-3486-a166-4b9358b732f7:{dialogueType:1,hearts:0,interactionFatigue:0,lastSeen:5L,playerUUID:[I;-910027387,1285567622,-1587131501,1488401143]}}(class net.minecraft.class_2487), new=-17(class java.lang.Integer)
	at net.minecraft.class_2945.method_12785(class_2945.java:245)
	at net.minecraft.class_2945.method_12779(class_2945.java:230)
	at net.minecraft.class_634.method_11093(class_634.java:460)
	at net.minecraft.class_2739.method_11808(class_2739.java:39)
	at net.minecraft.class_2739.method_11054(class_2739.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1085)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
]]></log4j:Throwable>
  </log4j:Event>`

**Comment by Luke100000** [comment]
For me this looks like incompatible versions, double check which version the server and client is running at

**Comment by Jurklein** [comment]
Server:
- release 1.18.2
- Fabric 0.14.9
- MCA Reborn 7.3.17 (fabric)
- Fabric API 0.58.0


Client:
- release 1.18.2
- Fabric 0.14.9
- MCA Reborn 7.3.17 (fabric)
- Fabric API 0.58.0

**Comment by Luke100000** [comment]
Hmm, should be fine. I assume the server restarted properly after changing mods?
Please send me both server and client logs, either here or any DM, so I can try to track that issue down.

**Comment by Jurklein** [comment]
I'm happy to tell that this behaviour ceased after I updated other library mods from the modpack list.
