### ISSUE TITLE
Refusing to launch client after installing MCA?

### ISSUE THREAD

**Issue by SmolGothic** [Luke100000/minecraft-comes-alive#474]
I honestly don't know how to fix what's going on with my game or how to fix it, I don't even get what the crash logs are telling me anymore and I did just about every fix I saw on here. I'm currently on forge version 1.19(41.0.45) and attempting to run MCA 7.3.17+1.19 with architectury 5.12.44. Help.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19-41.0.45-universal.jar%23180!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getVanillaFluidType(ForgeHooks.java:816) ~[forge-1.19-41.0.45-universal.jar%23180!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.material.Fluid.getFluidType(Fluid.java:108) ~[client-1.19-20220607.102129-srg.jar%23175!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury-common.mixins.json:inject.MixinFluid,pl:mixin:A}
	at net.minecraftforge.client.RenderProperties.get(RenderProperties.java:57) ~[forge-1.19-41.0.45-universal.jar%23180!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.getFluidMaterials(ForgeHooksClient.java:482) ~[forge-1.19-41.0.45-universal.jar%23180!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19-20220607.102129-srg.jar%23175!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1070) ~[client-1.19-20220607.102129-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:now-playing.mixins.common.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:now-playing.mixins.common.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.45.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?] {}

**Comment by cyuu22** [comment]
I had a similar issue, but after watching Epiko Xailia's video on the installation guide, I realized I had to download the Architectury mod AS WELL as the mca mod for versions later than 1.18.2. 

Here is the link in case you don't have it already:

https://www.curseforge.com/minecraft/mc-mods/architectury-api/files 

As soon as I installed this my game finally launched, so I hope this helps

**Comment by Luke100000** [comment]
1.19 is no longer supported and it looks like a incompatibility between forge or architectury and mca. MCA 1.19 is built with Architectury 5.6.21 and forge 41.0.16, you could try those versions.

**Comment by SmolGothic** [comment]
Thank you for your email! I will definitely try the specific versions
listed in this thread next time I try it :)
