### ISSUE TITLE
A problem lead to issue

### ISSUE THREAD

**Issue by moment-NEW** [Luke100000/minecraft-comes-alive#531]
**Describe the bug**
```
---- Minecraft Crash Report ----
// My bad.

Time: 2023/1/18 10:18
Description: Ticking entity

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1291.method_5573()'
	at fabric.net.mca.entity.VillagerEntityMCA.lambda$tickMovement$4(VillagerEntityMCA.java:721)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
	at fabric.net.mca.entity.VillagerEntityMCA.lambda$tickMovement$5(VillagerEntityMCA.java:721)
	at fabric.net.mca.util.InventoryUtils.getFirstSlotContainingItem(InventoryUtils.java:30)
	at fabric.net.mca.entity.VillagerEntityMCA.findAndEquipToMain(VillagerEntityMCA.java:751)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:719)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1646.method_5773(class_1646.java:313)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:767)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1589)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at fabric.net.mca.entity.VillagerEntityMCA.lambda$tickMovement$4(VillagerEntityMCA.java:721)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
	at fabric.net.mca.entity.VillagerEntityMCA.lambda$tickMovement$5(VillagerEntityMCA.java:721)
	at fabric.net.mca.util.InventoryUtils.getFirstSlotContainingItem(InventoryUtils.java:30)
	at fabric.net.mca.entity.VillagerEntityMCA.findAndEquipToMain(VillagerEntityMCA.java:751)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:719)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1646.method_5773(class_1646.java:313)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:767)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: mca:female_villager (fabric.net.mca.entity.VillagerEntityMCA)
	Entity ID: 4309
	Entity Name: Marija
	Entity's Exact location: -1287.41, 65.00, 1028.41
	Entity's Block location: World: (-1288,65,1028), Chunk: (at 8,4,4 in -81,64; contains blocks -1296,0,1024 to -1281,255,1039), Region: (-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to -1025,255,1535)
	Entity's Momentum: -0.07, -0.08, 0.06
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_1297.toString()" because the return value of "net.minecraft.class_1297.method_5854()" is null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['moment_new'/4304, l='ServerLevel[world]', x=-1287.87, y=63.00, z=1027.14]]
	Chunk stats: ServerChunkCache: 4050
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,67,225), Chunk: (at 0,4,1 in -9,14; contains blocks -144,0,224 to -129,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3284376 game time, 3299944 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 66876 (now: false), thunder time: 40841 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1589)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows Server 2022 (amd64) version 10.0
	Java Version: 19.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 906596352 bytes (864 MB) / 2130706432 bytes (2032 MB) up to 9663676416 bytes (9216 MB)
	CPUs: 2
	JVM Flags: 1 total; -Xmx9G
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		architectury: Architectury 1.32.66
		artifacts: Artifacts 4.0.2+fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		carrier: Carrier 1.7.6
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config2: Cloth Config v4 4.15.82
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		desolation: Desolation 1.1.2
		dragonloot: DragonLoot 1.0.6
		expandability: ExpandAbility 2.0.1
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.14.12
		fallflyinglib: FallFlyingLib 1.1.0
		farmersdelight: Farmer's Delight 1.16.5-0.0.7
		fastfurnace: FastFurnace 2.4
		fasttransferlib: Fast Transfer Lib 0.4.1
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.107
		graveyard: The Graveyard 1.1
		indrev: Industrial Revolution 1.9.17-BETA
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 19
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libgui: LibGui 3.4.0+1.16.5
		lithium: Lithium 0.6.6
		magna: Magna 0.2.1-1.16.5
		mca: Minecraft Comes Alive 7.3.22+1.16.5
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.4.0
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origin
[crash-2023-01-18_10.18.46-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10441941/crash-2023-01-18_10.18.46-server.txt)
s 0.7.3
		patchouli: Patchouli 1.16.4-50-FABRIC
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		spark: spark 1.6.0
		starlight: Starlight 0.0.3
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1
[crash-2023-01-17_15.41.18-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10441942/crash-2023-01-17_15.41.18-server.txt)
.2.3
		team_reborn_energy: Energy 0.1.1
		trinkets: Trinkets 2.6.7
		voidtotem: Void Totem (Fabric) 1.16.5-1.2.0
		voyager: Voyager 1.0.0
		waystones: Waystones 2.0.1
		wthit: wthit 2.10.15
		yigd: You're in Grave Danger 1.0.9
		yungsapi: YUNG's API 1.16.5-Fabric-7
	Player Count: 2 / 20; [class_3222['Pad_Na'/104, l='ServerLevel[world]', x=-314.34, y=37.00, z=249.96], class_3222['moment_new'/4304, l='ServerLevel[world]', x=-1287.87, y=63.00, z=1027.14]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by moment-NEW** [comment]
thanks！！！！！！！！！！could you please make the code to the kind of jar？I really need it.

**Comment by Luke100000** [comment]
Soon, if nothing distracts me it should be online today
