### ISSUE TITLE
mca reborn 7.3.22 & 7.3.23 keeps crashing

### ISSUE THREAD

**Issue by Sokraa** [Luke100000/minecraft-comes-alive#537]
crash code 
-1

crash msg
The game crashed whilst saving entity nbt
Error: java.lang.NullPointerException: Saving entity NBT

**Comment by Luke100000** [comment]
where log :)

**Comment by Sokraa** [comment]
oh sorry im newbie 

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 20.1.23 15:14
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:76) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:10) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStatsProvider.serializeNBT(PlayerStatsProvider.java:24) ~[?:3.0.4] {re:classloading,pl:capability_inject_definalize:A}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:113) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:122) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedPlayerList.func_72391_b(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72389_g(PlayerList.java:637) ~[?:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5845/946556798.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:76) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:10) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStatsProvider.serializeNBT(PlayerStatsProvider.java:24) ~[?:3.0.4] {re:classloading,pl:capability_inject_definalize:A}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:113) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:122) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
-- Entity being saved --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 256
	Entity Name: Sokraa
	Entity's Exact location: 61.50, 68.00, -253.50
	Entity's Block location: World: (61,68,-254), Chunk: (at 13,4,2 in 3,-16; contains blocks 48,0,-256 to 63,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedPlayerList.func_72391_b(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72389_g(PlayerList.java:637) ~[?:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5845/946556798.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
```

**Comment by Luke100000** [comment]
Thanks! Definitely an issue on weaponmasters side. Are you sure its mca related?

**Comment by Sokraa** [comment]
i dont really know i will try to run it without the weaponmasters :)

**Comment by Sokraa** [comment]
oh I runs completely fine without the wm, thx for advice and sorry 😅

**Comment by Luke100000** [comment]
No problem, glad its fixed ^^
