### ISSUE TITLE
Crash 7.4.7+1.19.2

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/minecraft-comes-alive#609]
```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
	at forge.net.mca.resources.Tasks.getRank(Tasks.java:71) ~[minecraft-comes-alive-7.4.7+1.19.2-universal.jar%23430!/:?] {re:classloading}
	at forge.net.mca.entity.VillagerEntityMCA.lambda$onDeath$7(VillagerEntityMCA.java:987) ~[minecraft-comes-alive-7.4.7+1.19.2-universal.jar%23430!/:?] {re:mixin,re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at forge.net.mca.entity.VillagerEntityMCA.m_6667_(VillagerEntityMCA.java:986) ~[minecraft-comes-alive-7.4.7+1.19.2-universal.jar%23430!/:?] {re:mixin,re:classloading}
```
https://discord.com/channels/747184859386085380/853442979812999189/1084234602090078318

**Comment by Luke100000** [comment]
Has to be an issue while dataloading, or modification by the player.
