### ISSUE TITLE
[Fabric 1.19.2] Server timeout Crash

### ISSUE THREAD

**Issue by grundyboy34** [Luke100000/minecraft-comes-alive#614]
**Describe the bug**
I have immersive portals, and sometimes when opening a portal to the nether, the server crashes due to a tick taking longer than 60 seconds with the stacktrace provided.
Importantly, this only happens on the server, not in singleplayer.

**To Reproduce**

**Screenshots**

**Version**
MCA Version: 7.4.7-1.19.2, 
Minecraft version: 1.19.2
Modloader: Fabric 0.14.17

**Latest.log**

>  Thread: Server Watchdog
>  Stacktrace:
>     at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
>     at java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
> 	at net.minecraft.class_1255.method_20813(class_1255.java:152)
> 	at net.minecraft.class_1255.method_18857(class_1255.java:142)
> 	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:2281)
> 	at net.minecraft.class_3215.method_12121(class_3215.java:2177)
> 	at net.minecraft.class_1937.method_8402(class_1937.java:197)
> 	at net.minecraft.class_1937.method_8497(class_1937.java:7078)
> 	at net.minecraft.class_1937.method_8320(class_1937.java:7570)
> 	at fabric.net.mca.server.ReaperSpawner.trySpawnReaper(ReaperSpawner.java:78)
> 	at net.minecraft.class_3218.md61b37a$mca$lambda$onOnBlockChanged$0$f(class_3218.java:18227)
> 	at net.minecraft.class_3218$$Lambda$17994/0x0000000802098f50.run(Unknown Source)
> 	at net.minecraft.class_3738.run(class_3738.java:18)
> 	at net.minecraft.class_1255.redirect$ceb000$c2me-opts-scheduling$redirectExecuteTask(class_1255.java:521)
> 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
> 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:13777)
> 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
> 	at net.minecraft.class_1255.method_5383(class_1255.java:116)
> 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)

`

**Comment by grundyboy34** [comment]
Started getting this one as well:
`java.lang.Error: Watchdog
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at net.minecraft.class_1255.method_20813(class_1255.java:152)
	at net.minecraft.class_1255.method_18857(class_1255.java:142)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:2281)
	at net.minecraft.class_3215.method_12121(class_3215.java:2177)
	at net.minecraft.class_1937.method_8402(class_1937.java:197)
	at net.minecraft.class_5715.method_32950(class_5715.java:68)
	at net.minecraft.class_5715.method_42336(class_5715.java:58)
	at net.minecraft.class_5715$$Lambda$22406/0x0000000802913a10.accept(Unknown Source)
	at java.base@17.0.3/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_5715.method_32952(class_5715.java:54)
	at net.minecraft.class_5715.method_42335(class_5715.java:27)
	at net.minecraft.class_3218$class_5526$$Lambda$20525/0x0000000802697748.accept(Unknown Source)
	at net.minecraft.class_7298.method_42147(class_7298.java:440)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1578)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1538)
	at net.minecraft.class_5579.method_31847(class_5579.java:217)
	at net.minecraft.class_5579.method_31820(class_5579.java:187)
	at net.minecraft.class_5579.method_31863(class_5579.java:204)
	at net.minecraft.class_5579$$Lambda$22244/0x00000008028e0f40.accept(Unknown Source)
	at net.minecraft.class_1299$1.method_31491(class_1299.java:553)
	at net.minecraft.class_1299$1$$Lambda$20030/0x000000080259f430.apply(Unknown Source)
	at java.base@17.0.3/java.util.Optional.map(Optional.java:260)
	at net.minecraft.class_1299.method_17842(class_1299.java:530)
	at net.minecraft.class_1299$1.method_31490(class_1299.java:552)
	at net.minecraft.class_1299$1$$Lambda$20029/0x000000080259f200.accept(Unknown Source)
	at java.base@17.0.3/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at net.minecraft.class_1299$1.tryAdvance(class_1299.java:551)
	at java.base@17.0.3/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base@17.0.3/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5579.method_31835(class_5579.java:204)
	at net.minecraft.class_3218.method_31426(class_3218.java:1524)
	at net.minecraft.class_3898.method_31413(class_3898.java:721)
	at net.minecraft.class_3898.method_31415(class_3898.java:740)
	at net.minecraft.class_3898$$Lambda$21841/0x0000000802868b48.run(Unknown Source)
	at net.minecraft.class_2818.method_12206(class_2818.java:434)
	at net.minecraft.class_3898.method_17227(class_3898.java:745)
	at net.minecraft.class_3898$$Lambda$19991/0x00000008025938b0.apply(Unknown Source)
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at com.mojang.datafixers.util.Either$$Lambda$19654/0x000000080252c9e8.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at net.minecraft.class_3898.method_20460(class_3898.java:733)
	at net.minecraft.class_3898$$Lambda$19988/0x0000000802593230.apply(Unknown Source)
	at java.base@17.0.3/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base@17.0.3/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3900$$Lambda$19963/0x000000080258f188.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:2281)
	at net.minecraft.class_3215.method_12121(class_3215.java:2177)
	at net.minecraft.class_1937.method_8402(class_1937.java:197)
	at net.minecraft.class_1937.method_22350(class_1937.java:7068)
	at net.minecraft.class_1937.method_8500(class_1937.java:7063)
	at net.minecraft.class_1937.method_8404(class_1937.java:900)
	at fabric.net.mca.util.WorldUtils.spawnEntity(WorldUtils.java:50)
	at fabric.net.mca.entity.VillagerFactory.spawn(VillagerFactory.java:104)
	at fabric.net.mca.server.SpawnQueue.tick(SpawnQueue.java:47)
	at fabric.net.mca.server.world.data.VillageManager.tick(VillageManager.java:173)
	at fabric.net.mca.fabric.MCAFabric.lambda$onInitialize$0(MCAFabric.java:49)
	at fabric.net.mca.fabric.MCAFabric$$Lambda$13187/0x0000000801c88000.onEndTick(Unknown Source)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$6023/0x0000000800f05a78.onEndTick(Unknown Source)
	at net.minecraft.class_3218.handler$dah000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:10729)
	at net.minecraft.class_3218.method_18765(class_3218.java:384)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$19045/0x00000008023827d0.run(Unknown Source)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)`
