### ISSUE TITLE
Bug on start MCA in 1.19.4

### ISSUE THREAD

**Issue by PhoenixGhost141** [Luke100000/minecraft-comes-alive#615]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'mca'!

When starting Minecraft 1.19.4, it gives me the aforementioned error, I hope it is useful, since I use the latest versions of Architecture, etc., I already tried with previous versions, but I still get the same thing...

```
[14:48:37] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.17
[14:48:38] [main/INFO]: Loading 124 mods:
	- architectury 8.1.72
	- bettercombat 1.6.2+1.19.3
	- betterdeserttemples 1.19.3-Fabric-2.3.0
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.19.3-Fabric-3.3.0
	- betterfortresses 1.19.3-Fabric-1.1.1
	- bettermineshafts 1.19.3-Fabric-3.3.0
	- betteroceanmonuments 1.19.3-Fabric-2.2.0
	- cinderscapes 3.2.0-alpha.1
	   |-- biolith 0.0.1-alpha.3
	   |    \-- terraform-surfaces-api-v1 6.0.0-beta.2
	   |-- cinderscapes-client 3.2.0-alpha.1
	   |-- cinderscapes-common 3.2.0-alpha.1
	   |-- cinderscapes-worldgen 3.2.0-alpha.1
	   |-- terraform-biome-remapper-api-v1 6.0.0-beta.2
	   |-- terraform-shapes-api-v1 6.0.0-beta.2
	   |-- terraform-surfaces-api-v1 6.0.0-beta.2
	   \-- terraform-wood-api-v1 6.0.0-beta.2
	- cloth-config 10.0.96
	   \-- cloth-basic-math 0.6.1
	- combatroll 1.1.5+1.19.3
	- creativecore 2.10.7
	   \-- net_minecraftforge_eventbus 6.0.4
	- ctov 3.1.8
	- fabric-api 0.76.0+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-command-api-v2 2.2.4+ae0966baf4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.52+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   |-- fabric-networking-v0 0.3.39+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabricloader 0.14.17
	- ferritecore 5.2.0
	- figura 0.1.0-rc.14+1.19.4-b2082be
	   |-- com_github_moonlight-mc_luaj_luaj-core 3.0.5-figura
	   |-- com_github_moonlight-mc_luaj_luaj-jse 3.0.5-figura
	   \-- org_java-websocket_java-websocket 1.5.2
	- geckolib 4.1.0
	   \-- com_eliotlash_mclib_mclib 20
	- immersive_aircraft 0.4.1+1.19.3
	- indium 1.0.15+mc1.19.4
	- iris 1.5.2
	   |-- io_github_douira_glsl-transformer 2.0.0-pre9
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- krypton 0.2.2
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lithium 0.11.1
	- manic_mr 1.0.3
	- mca 7.4.7+1.19.3
	- minecraft 1.19.4
	- mob_captains_mr 1-v2.1.0
	- modmenu 6.1.0-rc.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   \-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	- notenoughanimations 1.6.3
	- player-animator 1.0.2+1.19.4-rc2
	- reeses-sodium-options 1.5.0+mc1.19.4-build.72
	- scout 1.1.2
	- skinlayers 1.5.3-mc1.19.4
	- sodium 0.4.10+build.24
	- sodium-extra 0.4.18+mc1.19.4-build.100
	   |-- caffeineconfig 1.1.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.1+fabric.ae22326
	- terrablender 2.2.0.154
	   |-- com_electronwill_night-config_core 3.6.4
	   \-- com_electronwill_night-config_toml 3.6.4
	- toolleveling 1.19.3-1.4.3
	- traverse 6.2.0-alpha.1
	   |-- biolith 0.0.1-alpha.3
	   |    \-- terraform-surfaces-api-v1 6.0.0-beta.2
	   |-- terraform-biome-remapper-api-v1 6.0.0-beta.2
	   |-- terraform-config-api-v1 6.0.0-beta.2
	   |-- terraform-surfaces-api-v1 6.0.0-beta.2
	   |-- terraform-tree-api-v1 6.0.0-beta.2
	   |-- terraform-wood-api-v1 6.0.0-beta.2
	   |-- traverse-client 6.2.0-alpha.1
	   |-- traverse-common 6.2.0-alpha.1
	   \-- traverse-worldgen 6.2.0-alpha.1
	- trinkets 3.6.0
	   |-- cardinal-components-base 5.1.0
	   \-- cardinal-components-entity 5.1.0
	- vcinteraction 1.19.4-1.0.3
	   \-- polymer-registry-sync-manipulator 0.4.0+1.19.4
	- voicechat 1.19.4-2.3.28
	- yungsapi 1.19.3-Fabric-3.9.0
	   \-- org_javassist_javassist 3.28.0-GA
[14:48:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/schmi/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:48:39] [main/INFO]: Compatibility level set to JAVA_16
[14:48:39] [main/INFO]: Compatibility level set to JAVA_17
[14:48:40] [main/WARN]: Reference map 'cinderscapes-worldgen-refmap.json' for mixins.cinderscapes-worldgen.json could not be read. If this is a development environment you can ignore this message
[14:48:40] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 2 override(s) found
[14:48:40] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 3 override(s) found
[14:48:40] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[14:48:40] [main/WARN]: Reference map 'traverse-common-refmap.json' for mixins.traverse-common.json could not be read. If this is a development environment you can ignore this message
[14:48:42] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[14:48:42] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[14:48:42] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinCuboid' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[14:48:42] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinModelPart' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[14:48:42] [main/WARN]: Force-disabling mixin 'features.gui.font.MixinGlyphRenderer' as rule 'mixin.features.gui.font' (added by mods [iris]) disables it and children
[14:48:42] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[14:48:43] [main/WARN]: Error loading class: net/minecraft/class_809$class_811 (java.lang.ClassNotFoundException: net/minecraft/class_809$class_811)
[14:48:58] [Datafixer Bootstrap/INFO]: 180 Datafixer optimizations took 406 milliseconds
[14:49:02] [Render thread/INFO]: Launching a new process to probe the system configuration!
[14:49:03] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[14:49:03] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 960/PCIe/SSE2
[14:49:03] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 531.18
[14:49:03] [Render thread/WARN]: Enabling workaround for NVIDIA graphics drivers on Windows (issue #1486)
[14:49:03] [Render thread/WARN]: One or more workarounds were enabled to prevent crashes or other issues on your system. You may need to update your graphics drivers.
[14:49:04] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:49:05] [Render thread/INFO]: Setting user: PhoenixGhost141
[14:49:06] [Render thread/INFO]: Reflections took 129 ms to scan 1 urls, producing 1 keys and 2 values
[14:49:06] [Render thread/INFO]: Reflections took 4 ms to scan 1 urls, producing 1 keys and 2 values
[14:49:06] [Render thread/INFO]: Reflections took 4 ms to scan 1 urls, producing 1 keys and 3 values
[14:49:06] [Render thread/INFO]: Reflections took 2 ms to scan 1 urls, producing 1 keys and 3 values
[14:49:07] [Render thread/INFO]: Reflections took 1 ms to scan 1 urls, producing 1 keys and 1 values
[14:49:07] [Render thread/INFO]: Reflections took 1 ms to scan 1 urls, producing 1 keys and 1 values
[14:49:07] [Render thread/INFO]: Reflections took 1 ms to scan 1 urls, producing 1 keys and 2 values
[14:49:07] [Render thread/INFO]: Reflections took 1 ms to scan 1 urls, producing 1 keys and 2 values
[14:49:07] [Render thread/INFO]: Reflections took 1 ms to scan 1 urls, producing 1 keys and 1 values
[14:49:07] [Render thread/INFO]: Reflections took 1 ms to scan 1 urls, producing 1 keys and 1 values
[14:49:07] [Render thread/INFO]: Biolith is loaded!
[14:49:07] [Render thread/INFO]: Enabling Cinderscapes' Biolith worldgen module.
[14:49:07] [Render thread/ERROR]: No data fixer registered for immersive_aircraft:gyrodyne
[14:49:07] [Render thread/ERROR]: No data fixer registered for immersive_aircraft:biplane
[14:49:07] [Render thread/ERROR]: No data fixer registered for immersive_aircraft:airship
[14:49:07] [Render thread/ERROR]: No data fixer registered for immersive_aircraft:quadrocopter
[14:49:07] [Render thread/INFO]: Compression will use Java, encryption will use Java
[14:49:08] [Render thread/ERROR]: No data fixer registered for mca:tombstone
[14:49:08] [Render thread/ERROR]: No data fixer registered for mca:male_villager
[14:49:08] [Render thread/ERROR]: No data fixer registered for mca:female_villager
[14:49:08] [Render thread/ERROR]: No data fixer registered for mca:male_zombie_villager
[14:49:08] [Render thread/ERROR]: No data fixer registered for mca:female_zombie_villager
[14:49:08] [Render thread/ERROR]: No data fixer registered for mca:grim_reaper
[14:49:08] [Render thread/INFO]: Registered region minecraft:overworld to index 0 for type OVERWORLD
[14:49:08] [Render thread/INFO]: Registered region minecraft:nether to index 0 for type NETHER
[14:49:08] [Render thread/INFO]: Registered region traverse:overworld to index 1 for type OVERWORLD
[14:49:08] [Render thread/INFO]: Enabling Traverse's TerraBlender worldgen module.
[14:49:08] [Render thread/INFO]: Compatibility version 15
[14:49:08] [Render thread/INFO]: Loading plugins
[14:49:08] [Render thread/INFO]: Loaded 1 plugin(s)
[14:49:08] [Render thread/INFO]: Initializing plugins
[14:49:08] [Render thread/INFO]: Initialized 1 plugin(s)
[14:49:08] [Render thread/INFO]: Registering events for vcinteraction
[14:49:08] [Render thread/INFO]: Reflections took 4 ms to scan 1 urls, producing 1 keys and 4 values
[14:49:08] [Render thread/INFO]: Reflections took 4 ms to scan 1 urls, producing 1 keys and 4 values
[14:49:08] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[14:49:09] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[14:49:09] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[14:49:10] [ForkJoinPool.commonPool-worker-1/INFO]: Fetching backend resources...
[14:49:10] [Render thread/INFO]: Krypton is now accelerating your Minecraft client's networking stack ?
[14:49:10] [Render thread/INFO]: Note that Krypton is most effective on servers, not the client.
[14:49:10] [Render thread/ERROR]: Mixin apply for mod mca failed fabric-mca.mixin.json:client.MixinHeldItemFeatureRenderer from mod mca -> net.minecraft.class_989: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_4192 in fabric-mca.mixin.json:client.MixinHeldItemFeatureRenderer from mod mca was not located in the target class net.minecraft.class_989. Using refmap fabric-minecraft-comes-alive-common-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_4192 in fabric-mca.mixin.json:client.MixinHeldItemFeatureRenderer from mod mca was not located in the target class net.minecraft.class_989. Using refmap fabric-minecraft-comes-alive-common-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at fabric.net.mca.fabric.MCAFabricClient.onInitializeClient(MCAFabricClient.java:49) ~[minecraft-comes-alive-7.4.7+1.19.3-universal.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.14.17.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:468) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) ~[fabric-loader-0.14.17-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
[14:49:10] [Render thread/INFO]: Using Cloth Config GUI
[14:49:10] [Worker-Main-1/INFO]: Checking mod updates...
```

**Comment by Luke100000** [comment]
Don't use 1.19.3 mods on 1.19.4 and vice versa. Either downgrade fabric or wait for 1.19.4
