### ISSUE TITLE
Crash report with a bunch of other mods. 1.19.2

### ISSUE THREAD

**Issue by Chris-Creates** [Luke100000/minecraft-comes-alive#634]
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-04-20 01:01:48
Description: Colliding entity with block

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.ThreadLocal.get()" is null
	at net.minecraft.class_1309.handler$zcl000$porting_lib_base$port_lib$spawnDropsTAIL(class_1309.java:4201)
	at net.minecraft.class_1309.method_16080(class_1309.java:1397)
	at net.minecraft.class_1309.method_6078(class_1309.java:1348)
	at net.minecraft.class_3988.method_6078(class_3988.java:203)
	at net.minecraft.class_1646.method_6078(class_1646.java:656)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6078(VillagerEntityMCA.java:948)
	at net.minecraft.class_1309.method_5643(class_1309.java:1204)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5643(VillagerEntityMCA.java:675)
	at net.minecraft.class_3830.method_9548(class_3830.java:86)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952)
	at net.minecraft.class_1297.method_5852(class_1297.java:1059)
	at net.minecraft.class_1297.method_36974(class_1297.java:783)
	at net.minecraft.class_1297.method_5784(class_1297.java:752)
	at net.minecraft.class_1309.method_26318(class_1309.java:2282)
	at net.minecraft.class_1309.method_6091(class_1309.java:2227)
	at net.minecraft.class_1309.method_6007(class_1309.java:2680)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:698)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:765)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1309.handler$zcl000$porting_lib_base$port_lib$spawnDropsTAIL(class_1309.java:4201)
	at net.minecraft.class_1309.method_16080(class_1309.java:1397)
	at net.minecraft.class_1309.method_6078(class_1309.java:1348)
	at net.minecraft.class_3988.method_6078(class_3988.java:203)
	at net.minecraft.class_1646.method_6078(class_1646.java:656)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6078(VillagerEntityMCA.java:948)
	at net.minecraft.class_1309.method_5643(class_1309.java:1204)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5643(VillagerEntityMCA.java:675)
	at net.minecraft.class_3830.method_9548(class_3830.java:86)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952)
	at net.minecraft.class_1297.method_5852(class_1297.java:1059)
	at net.minecraft.class_1297.method_36974(class_1297.java:783)
	at net.minecraft.class_1297.method_5784(class_1297.java:752)
	at net.minecraft.class_1309.method_26318(class_1309.java:2282)
	at net.minecraft.class_1309.method_6091(class_1309.java:2227)
	at net.minecraft.class_1309.method_6007(class_1309.java:2680)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:698)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:765)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Block being collided with --
Details:
	Block: Block{minecraft:sweet_berry_bush}[age=3]
	Block location: World: (730,63,-148), Section: (at 10,15,12 in 45,3,-10; chunk contains blocks 720,-64,-160 to 735,319,-145), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
Stacktrace:
	at net.minecraft.class_1297.method_5852(class_1297.java:1059)
	at net.minecraft.class_1297.method_36974(class_1297.java:783)
	at net.minecraft.class_1297.method_5784(class_1297.java:752)
	at net.minecraft.class_1309.method_26318(class_1309.java:2282)
	at net.minecraft.class_1309.method_6091(class_1309.java:2227)
	at net.minecraft.class_1309.method_6007(class_1309.java:2680)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:698)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:765)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Entity being checked for collision --
Details:
	Entity Type: mca:male_villager (fabric.net.mca.entity.VillagerEntityMCA)
	Entity ID: 4957
	Entity Name: Marlen
	Entity's Exact location: 730.37, 63.00, -147.41
	Entity's Block location: World: (730,63,-148), Section: (at 10,15,12 in 45,3,-10; chunk contains blocks 720,-64,-160 to 735,319,-145), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_36974(class_1297.java:783)
	at net.minecraft.class_1297.method_5784(class_1297.java:752)
	at net.minecraft.class_1309.method_26318(class_1309.java:2282)
	at net.minecraft.class_1309.method_6091(class_1309.java:2227)
	at net.minecraft.class_1309.method_6007(class_1309.java:2680)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at fabric.net.mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:698)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:765)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Entity being ticked --
Details:
	Entity Type: mca:male_villager (fabric.net.mca.entity.VillagerEntityMCA)
	Entity ID: 4957
	Entity Name: Marlen
	Entity's Exact location: 730.37, 63.00, -147.41
	Entity's Block location: World: (730,63,-148), Section: (at 10,15,12 in 45,3,-10; chunk contains blocks 720,-64,-160 to 735,319,-145), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Da_Fleegsta'/3490, l='ServerLevel[New World]', x=732.17, y=63.00, z=-170.60]]
	Chunk stats: 4346
	Level dimension: minecraft:overworld
	Level spawn location: World: (464,68,-336), Section: (at 0,4,0 in 29,4,-21; chunk contains blocks 464,-64,-336 to 479,319,-321), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 3223 game time, 3223 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 68385 (now: false), thunder time: 164994 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 831910392 bytes (793 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6600 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: DriverVersion=31.0.12029.10015
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32718.74
	Virtual memory used (MB): 27083.77
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19.2
		aqupdgrizzly: Grizzly Bear mob 1.19.2-1.3
		architectury: Architectury 6.5.77
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.7
		better_respawn: Better Respawn 1.19.2-2.0.2
		better_wandering_trader: Better Wandering Trader 1.8.0
		bettercombat: Better Combat 1.6.2+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bettervillage: Better village 3.0.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bountiful: Bountiful 3.0.0
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		carryon: Carry On 2.0.4.6
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.53
		combatroll: Combat Roll 1.1.5+1.19
		comforts: Comforts 6.0.4+1.19.2
			spectrelib: SpectreLib 0.12.4+1.19.2
		configured: Configured 2.0.0
		controlling: Controlling For Fabric 10.0+7
		coord_book: Coordinate Book 1.2.1
		creeperoverhaul: Creeper Overhaul 2.0.9
		ctov: ChoiceTheorem's Overhauled Villages 3.1.8
		dehydration: Dehydration 1.3.4
		environmentalcreepers: Environmental Creepers 1.6.0
		environmentz: EnvironmentZ 2.0.0
			satin: Satin 1.9.0
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.3+kotlin.1.8.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		fabricshieldlib: Fabric Shield Lib 1.7-1.19.2
			mm: Manningham Mills 2.3
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frostiful: Frostiful 0.4.2
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		goblintraders: Goblin Traders 1.8.1
		herdspanic: Herds Panic 1.0.6
		incendium: Incendium 5.1.4
		indypets: IndyPets - Independent Pets 1.1.0-1.19.2
		jamlib: JamLib 0.6.0+1.19
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1015
		jeresources: Just Enough Resources 1.1.0.179
		jmi: JourneyMapIntegration 0.13-33
		journeymap: Journeymap 5.9.5
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		kambrik: Kambrik 4.0-1.19.2
		libertyvillagers: Liberty's Villagers 1.0.14+fabric+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		libraryferret: Library ferret 4.0.0
		litematica: Litematica 0.12.7
		malilib: MaLiLib 0.13.0
		mapfrontiers: MapFrontiers 2.5.0-beta2-fabric
		mca: Minecraft Comes Alive 7.4.8+1.19.2
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		modsettings: ModSettings 1.1.0+1.19
		morebannerfeatures: More Banner Features 1.1.3
		moreleads: Moreleads 1.19.2-1.0.0
		mostructures: Mo' Structures 1.4.3+1.19.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		mythicmounts: Mythic Mounts 1.19.2-7.1
		naturalist: Naturalist 3.0.1
		no-shield-delay: No Shield Delay 1.0.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2
		polymorph: Polymorph 0.46.1+1.19.2
		projectsavethepets: Project: Save the Pets! 3.2.0+2022.e000b2a529.fabric
		puddles: Puddles 1.2.2
		realisticfirespread: Realistic Fire Spread 1.19-2
		repurposed_structures: Repurposed Structures 6.3.21+1.19.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		resourcefulconfig: Resourcefulconfig 1.0.20
		rocks: This Rocks! 1.6.1
		rottencreatures: Rotten Creatures 1.0.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		skyvillages: Sky Villages 1.0.2.1
		smallships: Small Ships 2.0.0a1.1.1
		spiceoffabric: Spice of Fabric 1.6.0-beta.4+1.19.2
			capsaicin: Capsaicin 1.3.1+mc1.19.3
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		stendhal: Stendhal 1.3.4-1.19
		stoneholm: Stoneholm 1.4.4
		survival_campfire: Survival Campfire 0.0.1
		t_and_t: Towns and Towers 1.10
			blue_endless_jankson: jankson 1.2.1
		tame_them_all: Tame Them All 1.0.0
			porting_lib: Porting Lib 2.1.706+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.706+1.19.2
					porting_lib_entity: Porting Lib Entity 2.1.706+1.19.2
					porting_lib_fake_players: Porting Lib Fake Players 2.1.706+1.19.2
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.706+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.706+1.19.2
					porting_lib_models: Porting Lib Models 2.1.706+1.19.2
						porting_lib_obj_loader: Porting Lib Obj Loader 2.1.706+1.19.2
							porting_lib_model_loader: Porting Lib Model Loader 2.1.706+1.19.2
						porting_lib_transfer: Porting Lib Transfer 2.1.706+1.19.2
							porting_lib_extensions: Porting Lib Extensions 2.1.706+1.19.2
								porting_lib_accessors: Porting Lib Accessors 2.1.706+1.19.2
								porting_lib_attributes: Porting Lib Attributes 2.1.706+1.19.2
									porting_lib_constants: Porting Lib Constants 2.1.706+1.19.2
								porting_lib_common: Porting Lib Common 2.1.706+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.706+1.19.2
		tawct: Time & Wind Custom Ticker 1.4.3+1.19.2
		terrablender: TerraBlender 2.0.1.136
		terralith: Terralith 2.3
		travelerstitles: Traveler's Titles 1.19.2-Fabric-3.1.0
		treeharvester: Tree Harvester 8.0
		trinkets: Trinkets 3.4.2
		utilitybelt: Utility Belt 1.2.0
		villagerquests: Villager Quests 1.0.7
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		wandering_trapper: Wandering Trapper 2.0.0
		waveycapes: WaveyCapes 1.3.2
		waystones: Waystones 11.3.1
		wthit: wthit 5.15.2
		wwoo: William Wythers' Overhauled Overworld 3.1.9.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['Da_Fleegsta'/3490, l='ServerLevel[New World]', x=732.17, y=63.00, z=-170.60]]
	Data Packs: vanilla, Fabric Mods, t_and_t_waystones_patch_1.19.2.zip
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.19-1.19.2
```

**Comment by Luke100000** [comment]
Mod conflict caused by Porting Lib, will check that out later

**Comment by GodsTitan** [comment]
It mentions mca:male_villager in the crash report, leading me to think there is an incompatibility here as well. Is this the same issue?

https://gnomebot.dev/paste/1099507014436130836
https://gnomebot.dev/paste/1099507168421621760

**Comment by Luke100000** [comment]
> It mentions mca:male_villager in the crash report, leading me to think there is an incompatibility here as well. Is this the same issue?
> 
> https://gnomebot.dev/paste/1099507014436130836 https://gnomebot.dev/paste/1099507168421621760

This is a different compatibility, see this here: #267

**Comment by Luke100000** [comment]
Apparently fixed https://github.com/Fabricators-of-Create/Porting-Lib/issues/29

**Comment by Chris-Creates** [comment]
i'll try it thank you
