### ISSUE TITLE
java.lang.ArithmeticException: / by zero | 1.17.1

### ISSUE THREAD

**Issue by AndreyRGW** [Luke100000/minecraft-comes-alive#666]
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 26.05.2023, 18:25
Description: Exception ticking world

java.lang.ArithmeticException: / by zero
	at java.base/java.lang.Math.floorMod(Math.java:1583)
	at fabric.net.mca.resources.Names.pickCitizenName(Names.java:57)
	at fabric.net.mca.entity.ZombieVillagerFactory.lambda$build$0(ZombieVillagerFactory.java:96)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at fabric.net.mca.entity.ZombieVillagerFactory.build(ZombieVillagerFactory.java:96)
	at fabric.net.mca.entity.ZombieVillagerFactory.spawn(ZombieVillagerFactory.java:87)
	at fabric.net.mca.server.SpawnQueue.tick(SpawnQueue.java:61)
	at fabric.net.mca.server.world.data.VillageManager.tick(VillageManager.java:182)
	at fabric.net.mca.fabric.MCAFabric.lambda$onInitialize$0(MCAFabric.java:48)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_1937.handler$zhf000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_1937.java:1594)
	at net.minecraft.class_1937.method_18471(class_1937.java:479)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1623)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.lang.Math.floorMod(Math.java:1583)
	at fabric.net.mca.resources.Names.pickCitizenName(Names.java:57)
	at fabric.net.mca.entity.ZombieVillagerFactory.lambda$build$0(ZombieVillagerFactory.java:96)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at fabric.net.mca.entity.ZombieVillagerFactory.build(ZombieVillagerFactory.java:96)
	at fabric.net.mca.entity.ZombieVillagerFactory.spawn(ZombieVillagerFactory.java:87)
	at fabric.net.mca.server.SpawnQueue.tick(SpawnQueue.java:61)
	at fabric.net.mca.server.world.data.VillageManager.tick(VillageManager.java:182)
	at fabric.net.mca.fabric.MCAFabric.lambda$onInitialize$0(MCAFabric.java:48)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_1937.handler$zhf000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_1937.java:1594)
	at net.minecraft.class_1937.method_18471(class_1937.java:479)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)

-- Affected level --
Details:
	All players: 1 total; [class_3222['AndreyRGW'/206, l='ServerLevel[world1]', x=-173.63, y=71.75, z=18.30]]
	Chunk stats: 2518
	Level dimension: minecraft:overworld
	Level spawn location: World: (-58,66,52), Section: (at 6,2,4 in -4,4,3; chunk contains blocks -64,0,48 to -49,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 64820 game time, 75025 day time
	Level name: world1
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 66 (now: false), thunder time: 25835 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1623)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 20.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 5708447744 bytes (5444 MiB) / 7088373760 bytes (6760 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3,70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3129
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 3,60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 58294,59
	Virtual memory used (MB): 47674,55
	Swap memory total (MB): 25600,00
	Swap memory used (MB): 6362,36
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:-ZUncommit -XX:ZCollectionInterval=5 -XX:ZAllocationSpikeTolerance=2.0 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -Xms2048M -Xmx8192M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		architectury: Architectury 2.10.12
		baritone: Baritone 1.7.3
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config2: Cloth Config v5 5.3.63
		custom-fog: Custom Fog 2.0.0
		customstars: Custom Stars 0.7+1.17
		customvoid: Custom Void 0.5+1.17
		fabric: Fabric API 0.46.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+e821752d18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.15+b556f28c18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.0+ea29b33318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+ce16ae5918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.10+ce16ae5918
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+591a0f2118
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.2.0+48a9ad8918
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.3+3b96517518
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+cf39a74318
		fabricloader: Fabric Loader 0.14.19
		iris: Iris 1.2.7
		java: OpenJDK 64-Bit Server VM 20
		lambdynlights: LambDynamicLights 2.0.2+1.17
		mca: Minecraft Comes Alive 7.3.22+1.17.1
		minecraft: Minecraft 1.17.1
		modern_beta: Modern Beta Fabric 2.8.3+1.17.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		roughlyenoughitems: Roughly Enough Items 6.5.433
		sodium: Sodium 0.3.4+build.13
		spruceui: SpruceUI 3.2.0+1.17
		wagyourminimap: WagYourMinimap 1.0.11+1.17.1-fabric
	Loaded Shaderpack: (off)
	Player Count: 1 / 8; [class_3222['AndreyRGW'/206, l='ServerLevel[world1]', x=-173.63, y=71.75, z=18.30]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by Luke100000** [comment]
I suspect errors before the crash, please append the latest.log

**Comment by AndreyRGW** [comment]
After deleting the mca.json file there are no more crashes.
