### ISSUE TITLE
Crash when saving and returning to menu (Skin Shuffle compatibility) (1.20.1)

### ISSUE THREAD

**Issue by WimpieRatte** [Luke100000/minecraft-comes-alive#720]
**Describe the bug**
When both MCA and Skin Shuffle is installed, when I save my world and go back to the main menu, the game crashes.

**Version**
MCA Version: 7.5.3
Minecraft version: 1.20.1
Modloader: Prismlauncher

**Latest.log**
Attached.
[crash-2023-07-27_01.51.11-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/12178235/crash-2023-07-27_01.51.11-client.txt)

Stacktrace snippet:
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking.send(ClientPlayNetworking.java:370)
	at fabric.net.mca.fabric.cobalt.network.NetworkHandlerImpl.sendToServer(NetworkHandlerImpl.java:48)
	at fabric.net.mca.cobalt.network.NetworkHandler.sendToServer(NetworkHandler.java:13)
	at fabric.net.mca.MCAClient.useGeneticsRenderer(MCAClient.java:33)
	at net.minecraft.class_1007.handler$elg000$mca$injectScale(class_1007.java:4068)
	at net.minecraft.class_1007.method_4217(class_1007.java:156)
	at net.minecraft.class_1007.method_4042(class_1007.java:43)
	at net.minecraft.class_922.method_4054(class_922.java:107)
	at net.minecraft.class_1007.method_4215(class_1007.java:66)
	at net.minecraft.class_1007.method_3936(class_1007.java:43)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:84)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:56)
	at com.mineblock11.skinshuffle.client.gui.widgets.OpenCarouselButton.method_25394(OpenCarouselButton.java:84)
	at net.minecraft.class_437.method_25394(class_437.java:120)
	at net.minecraft.class_442.method_25394(class_442.java:289)
	at net.minecraft.class_437.method_47413(class_437.java:110)

**Comment by Luke100000** [comment]
Merged with #714
