### ISSUE TITLE
Sorting state uninitialized

### ISSUE THREAD

**Issue by Guyao146** [Luke100000/minecraft-comes-alive#739]
**Describe the bug**

**To Reproduce**
login my server
client crash

**Screenshots**

**Version**
minecraft 1.20.1
forge 47.1.3
mohist 1.20.1-311
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12318118/latest.log)

**Latest.log** client

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12318119/latest.log)

**Comment by Luke100000** [comment]
For me:
```
Caused by: java.lang.IllegalStateException: Sorting state uninitialized
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166786_(BufferBuilder.java:181) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at com.mojang.blaze3d.vertex.BufferBuilder.m_231177_(BufferBuilder.java:224) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at com.mojang.blaze3d.vertex.BufferBuilder.m_231175_(BufferBuilder.java:204) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.renderer.RenderType.m_276775_(RenderType.java:432) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109912_(MultiBufferSource.java:97) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109916_(MultiBufferSource.java:76) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109911_(MultiBufferSource.java:73) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280262_(GuiGraphics.java:125) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_286081_(GuiGraphics.java:93) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.GuiGraphics.drawString(GuiGraphics.java:298) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280649_(GuiGraphics.java:292) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280648_(GuiGraphics.java:288) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.components.EditBox.m_87963_(EditBox.java:405) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_88315_(AbstractWidget.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraft.client.gui.screens.Screen.m_88315_(Screen.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at forge.net.mca.client.gui.VillagerEditorScreen.m_88315_(VillagerEditorScreen.java:744) ~[%5BM%5D%5B凡家物语：重生%5D%20minecraft-comes-alive-7.5.5+1.20.1-universal.jar%23269!/:?]
	at forge.net.mca.client.gui.DestinyScreen.m_88315_(DestinyScreen.java:78) ~[%5BM%5D%5B凡家物语：重生%5D%20minecraft-comes-alive-7.5.5+1.20.1-universal.jar%23269!/:?]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.3-universal.jar%23315!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.3-universal.jar%23315!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?]
```

**Comment by Luke100000** [comment]
I can not track that issue down, please verify its not a mod conflict.
