### ISSUE TITLE
F3 Crashes my game

### ISSUE THREAD

**Issue by SergenteEnrico** [Luke100000/minecraft-comes-alive#871]
Everytime I Tried to load the MCA mod with Shaders and other mods, it does not let me show the F3 Information. I'm not sure it was the combination of other mods or shaders, or alone the mod.

**To Reproduce**
1. Add the Mods listed below 
(I had problems on 1.20.2, Avalight is "Alliance of Valiant Arms")
2. Create a world and talk to an Npc.
3. Press F3

Screenshots**

**Version**
MCA Version 7.5.12, +1.20.2-universal Minecraft 1.20.2, Modloader Forge 48.1.0

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/14320246/latest.log)
Hope this helps to understand. Have a nice day.

**Comment by SergenteEnrico** [comment]
> Everytime I Tried to load the MCA mod with Shaders and other mods, it does not let me show the F3 Information. I'm not sure it was the combination of other mods or shaders, or alone the mod.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add the Mods listed below
>    (I had problems on 1.20.2, Avalight is "Alliance of Valiant Arms")
> 2. Create a world and talk to an Npc.
> 3. Press F3
> 
>
> 
> **Version** MCA Version 7.5.12, +1.20.2-universal Minecraft 1.20.2, Modloader Forge 48.1.0
> 
> **Latest.log** [latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/14320246/latest.log) Hope this helps to understand. Have a nice day.

Forgot the mods, here they are.

![Screenshot (106)](https://github.com/Luke100000/minecraft-comes-alive/assets/160360472/f196045d-46e0-4f8a-963f-e6a774299842)

**Comment by Luke100000** [comment]
does it output a crash report as well? The log does not mention anything

**Comment by SergenteEnrico** [comment]
This is the crash report

```
// You're mean.

Time: 2024-02-20 09:30:52
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.client.gui.components.DebugScreenOverlay.update()'
	at net.minecraftforge.client.gui.overlay.ForgeGui$OverlayAccess.update(ForgeGui.java:528) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.renderHUDText(ForgeGui.java:359) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$18(VanillaGuiOverlay.java:161) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:105) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:101) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1345) ~[client-1.20.2-20230921.100330-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:forge-mca.mixin.json:client.MixinGameRenderer,pl:mixin:APP:avalight.mixins.json:client.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1211) ~[client-1.20.2-20230921.100330-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:781) ~[client-1.20.2-20230921.100330-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {}
	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at net.minecraftforge.client.gui.overlay.ForgeGui$OverlayAccess.update(ForgeGui.java:528) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.renderHUDText(ForgeGui.java:359) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$18(VanillaGuiOverlay.java:161) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:105) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:101) ~[forge-1.20.2-48.1.0-universal.jar%23191!/:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['SergentEnrico'/60, l='ClientLevel', x=-3161.28, y=69.00, z=-3488.48]]
	Chunk stats: 361, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (352,70,-1344), Section: (at 0,6,0 in 22,4,-84; chunk contains blocks 352,-64,-1344 to 367,319,-1329), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,-64,-1536 to 511,319,-1025)
	Level time: 1393638 game time, 1923954 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:568) ~[client-1.20.2-20230921.100330-srg.jar%23186!/:?] {re:classloading,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2395) ~[client-1.20.2-20230921.100330-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:803) ~[client-1.20.2-20230921.100330-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {}
	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: mod_resources, vanilla, high_contrast, file/Bare Bones 1.20.zip, file/Excalibur_V1.20.zip

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 580194776 bytes (553 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1273
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2520
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6262
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20499.30
	Virtual memory used (MB): 16683.75
	Swap memory total (MB): 4352.00
	Swap memory used (MB): 31.68
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	JVM uptime in seconds: 57.322
	Launched Version: 1.20.2-forge-48.1.0
	Backend library: LWJGL version 3.3.2+13
	Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 30.0.101.1273, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: mod_resources, vanilla, high_contrast, file/Bare Bones 1.20.zip (incompatible), file/Excalibur_V1.20.zip (incompatible)
	Current Language: en_gb
	Locale: it_IT
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['SergentEnrico'/60, l='ServerLevel[Modded_World_Family]', x=-3161.28, y=69.00, z=-3488.48]]
	Data Packs: vanilla, mod:jade (incompatible), mod:architectury (incompatible), mod:magical_torches, mod:additionallanterns (incompatible), mod:balm, mod:jei (incompatible), mod:spectrelib (incompatible), mod:supermartijn642corelib, mod:avalight, mod:workshop_for_handsome_adventurer (incompatible), mod:cloth_config (incompatible), mod:forge, mod:waystones, mod:collective, mod:dungeons_arise (incompatible), mod:comforts (incompatible), mod:travelersbackpack, mod:guardvillagers (incompatible), mod:mca (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	OptiFine Version: OptiFine_1.20.2_HD_U_I7_pre1
	OptiFine Build: 20231221-121621
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: miniature-shader-2.4.1.zip
	OpenGlVersion: 4.6.0 - Build 30.0.101.1273
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 16
	ModLauncher: 10.1.1
	ModLauncher launch target: forge_client
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.2.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.1.1.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.1.1.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.1.1.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.1.1.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@48
		javafml@null
	Mod List: 
		client-1.20.2-20230921.100330-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		guardvillagers-1.20.2-1.6.3.jar                   |Guard Villagers               |guardvillagers                |1.20.2-1.6.3        |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.2-forge-12.3.0.jar                      |Jade                          |jade                          |12.3.0              |DONE      |Manifest: NOSIGNATURE
		architectury-10.0.18-minecraftforge.jar           |Architectury                  |architectury                  |10.0.18             |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.12+1.20.2-universal.jar |Minecraft Comes Alive         |mca                           |7.5.12+1.20.2       |DONE      |Manifest: NOSIGNATURE
		MagicalTorches-1.20.2-2.0.3.jar                   |Magical Torches               |magical_torches               |2.0.3               |DONE      |Manifest: NOSIGNATURE
		additionallanterns-1.1.1-forge-mc1.20.jar         |Additional Lanterns           |additionallanterns            |1.1.1               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.2-8.0.5.jar                       |Balm                          |balm                          |8.0.5               |DONE      |Manifest: NOSIGNATURE
		jei-1.20.2-forge-16.0.0.2.jar                     |Just Enough Items             |jei                           |16.0.0.2            |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.14.1+1.20.2.jar                |SpectreLib                    |spectrelib                    |0.14.1+1.20.2       |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17-forge-mc1.20.2.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17              |DONE      |Manifest: NOSIGNATURE
		avalight-1.20.2-2.0.3.jar                         |A.V.A - Alliance of Valiant Ar|avalight                      |2.0.3               |DONE      |Manifest: NOSIGNATURE
		workshop_for_handsome_adventurer--mc1.20.2--1.10.j|Workshop for handsome adventur|workshop_for_handsome_adventur|1.10                |DONE      |Manifest: NOSIGNATURE
		cloth-config-12.0.119-forge.jar                   |Cloth Config v12 API          |cloth_config                  |12.0.119            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.2-48.1.0-universal.jar                 |Forge                         |forge                         |48.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		waystones-forge-1.20.2-15.2.0.jar                 |Waystones                     |waystones                     |15.2.0              |DONE      |Manifest: NOSIGNATURE
		collective-1.20.2-7.30.jar                        |Collective                    |collective                    |7.30                |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.20.x-2.1.58-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.58-1.20.x       |DONE      |Manifest: NOSIGNATURE
		comforts-forge-7.0.1+1.20.2.jar                   |Comforts                      |comforts                      |7.0.1+1.20.2        |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.20.2-9.2.4.jar                |Traveler's Backpack           |travelersbackpack             |9.2.4               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: edde4995-2cc1-4bd1-8d6c-8f5a5e63f0b6
	FML: 48.1
	Forge: net.minecraftforge:48.1.0
______________________________________________________________________________________________________________________________________
```
This is the exit code

-1073740791

**Comment by Luke100000** [comment]
Optifine appears to be incompatible with Forge 1.20.2 (see discussion over here https://github.com/cominixo/BetterF3/issues/164)

No open source mod, especially not mca, injects into that specific function. Except BetterF3 and afaik you do not have that one installed.

**Comment by SergenteEnrico** [comment]
Thank you, i'll implement it once i get home. Sorry to bother.

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
