### ISSUE TITLE
[1.18.1] Does not work with polymer?

### ISSUE THREAD

**Issue by itsdinkd** [Luke100000/minecraft-comes-alive#90]
Tried to use in my modpack, Another Quality Modpack 2, and it seems that RCA Reloaded prevents joining a single player world

```java
[19:30:53] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2945$class_2946.method_12794()" because the return value of "net.minecraft.class_2945.method_12783(net.minecraft.class_2940)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.2) ~[?:?]
	at net.minecraft.entity.data.DataTracker.get(DataTracker:118) ~[?:?]
	at mca.util.network.datasync.CDataParameter.get(CDataParameter.java:37) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.util.network.datasync.CDataManager.get(CDataManager.java:35) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.util.network.datasync.CTrackedEntity.getTrackedValue(CTrackedEntity.java:16) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.entity.VillagerEntityMCA.getCustomName(VillagerEntityMCA.java:900) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at net.minecraft.entity.Entity.getName(Entity:2409) ~[?:?]
	at net.minecraft.entity.Entity.getDisplayName(Entity:2653) ~[?:?]
	at mca.entity.VillagerEntityMCA.getDisplayName(VillagerEntityMCA.java:882) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at net.minecraft.entity.mob.MobEntity.handler$ejm000$constructor(MobEntity:8623) ~[?:?]
	at net.minecraft.entity.mob.MobEntity.<init>(MobEntity:145) ~[?:?]
	at net.minecraft.entity.mob.PathAwareEntity.<init>(PathAwareEntity:14) ~[?:?]
	at net.minecraft.entity.passive.PassiveEntity.<init>(PassiveEntity:28) ~[?:?]
	at net.minecraft.entity.passive.MerchantEntity.<init>(MerchantEntity:55) ~[?:?]
	at net.minecraft.entity.passive.VillagerEntity.<init>(VillagerEntity:195) ~[?:?]
	at net.minecraft.entity.passive.VillagerEntity.<init>(VillagerEntity:191) ~[?:?]
	at mca.entity.VillagerEntityMCA.<init>(VillagerEntityMCA.java:143) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.entity.EntitiesMCA.lambda$static$0(EntitiesMCA.java:18) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at net.minecraft.entity.EntityType.create(EntityType:475) ~[?:?]
	at mca.server.world.data.PlayerSaveData.resetEntityData(PlayerSaveData.java:100) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.server.world.data.PlayerSaveData.<init>(PlayerSaveData.java:71) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.server.world.data.PlayerSaveData.lambda$get$1(PlayerSaveData.java:64) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.util.WorldUtils.lambda$loadData$0(WorldUtils.java:39) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at net.minecraft.world.PersistentStateManager.getOrCreate(PersistentStateManager:48) ~[?:?]
	at mca.util.WorldUtils.loadData(WorldUtils.java:39) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.server.world.data.PlayerSaveData.get(PlayerSaveData.java:64) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.server.ServerInteractionManager.onPlayerJoin(ServerInteractionManager.java:53) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at mca.MCAFabric.lambda$onInitialize$3(MCAFabric.java:64) ~[minecraft-comes-alive-7.1.0-fabric.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.0.19+d7c144a865-27ddd48d544c3695.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.0.19+d7c144a865-27ddd48d544c3695.jar:?]
	at net.minecraft.server.PlayerManager.handler$epp000$handlePlayerConnection(PlayerManager:6963) ~[?:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:191) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler:130) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.md9153d0$lambda$polymer_prePlayHandshakeHackfest$0$0(ServerLoginNetworkHandler:1531) ~[?:?]
	at eu.pb4.polymer.impl.networking.PolymerHandshakeHandlerImplLogin.onKeepAlive(PolymerHandshakeHandlerImplLogin.java:137) ~[polymer-0.2.0-beta.20+1.18.1-8a0e90a6a20ae607.jar:?]
	at net.minecraft.network.packet.c2s.play.KeepAliveC2SPacket.apply(KeepAliveC2SPacket:15) ~[?:?]
	at net.minecraft.network.packet.c2s.play.KeepAliveC2SPacket.apply(KeepAliveC2SPacket:6) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:740) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ceo000$modifiedRunLoop(MinecraftServer:5365) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[client-intermediary.jar:?]```

**Comment by Luke100000** [comment]
Related to #89 , thanks for providing a modpack to test.

**Comment by Luke100000** [comment]
I tracked down the issue, in the case of this modpack `eldritch-mobs` is the cause. Compatibility should be restored in 7.1.1

**Comment by itsdinkd** [comment]
Good catch! Will add into official pack once updated on CF and tested :)
