### ISSUE TITLE
Launcher starting crash

### ISSUE THREAD

**Issue by alyr4** [Luke100000/minecraft-comes-alive#909]
I got a crash with mca when starting the launcher

	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: dev.architectury.registry.registries.RegistrySupplier
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 25 more
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (20 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1
flush now
flush now

basicly something like that

mca version is 7.5.14+1.20.1-universal
mc version is 1.20.1 (forge)

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
dont forget about architectury and include the log
