### ISSUE TITLE
Diagonal Panes Support

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/minecraft-comes-alive#955]
Basically adding modded iron bars to `mca:iron_bars`

**Comment by Luke100000** [comment]
Can't verify incompatibility with https://www.curseforge.com/minecraft/mc-mods/diagonal-panes

**Comment by Luke100000** [comment]
Can confirm with https://modrinth.com/mod/diagonal-windows but adding `diagonalwindows:minecraft/iron_bars` to the tags crashes puzzlelib?

```
Caused by: java.lang.IllegalStateException: target block tags not empty
	at fuzs.puzzleslib.api.block.v1.BlockConversionHelper.copyBoundTags(BlockConversionHelper.java:77) ~[PuzzlesLib-v8.1.21-1.20.1-Fabric.jar:?]
	at java.util.Map.forEach(Unknown Source) ~[?:?]
	at fuzs.diagonalblocks.handler.DiagonalBlockHandler.copyBoundTags(DiagonalBlockHandler.java:81) ~[diagonalblocks-8.0.5-2a28cf26f12759c3.jar:?]
	at fuzs.diagonalblocks.handler.DiagonalBlockHandler.onTagsUpdated(DiagonalBlockHandler.java:42) ~[diagonalblocks-8.0.5-2a28cf26f12759c3.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.CommonLifecycleEvents.lambda$static$0(CommonLifecycleEvents.java:33) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099849194dcb7e.jar:?]
	at net.minecraft.class_5350.handler$zhj000$fabric-lifecycle-events-v1$hookRefresh(class_5350.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_5350.method_40421(class_5350.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_42097(class_7237.java:57) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:188) ~[client-intermediary.jar:?]
```
